"""gove-zone: minimal governed agent runtime.

A small library that wraps AI agent tool calls with policy checks,
fail-closed decisions, replayable receipts, and a tamper-evident audit chain.
"""

from importlib import metadata as _metadata

from gove_zone.agent import ManagedAgent
from gove_zone.audit import GENESIS_HASH, AuditChainError, ChainHashAuditStore
from gove_zone.authz import (
    AuthzReason,
    AuthzRegistryError,
    PrincipalEntry,
    PrincipalRegistry,
    authz_enforce_from_env,
)
from gove_zone.benchmark_adapters import (
    agentdojo_scenarios_from_fixture,
    injecagent_scenarios_from_fixture,
    load_benchmark_suite,
)
from gove_zone.consumption import LedgerObservability, ReceiptConsumptionLedger
from gove_zone.contracts import (
    AuditEvent,
    ExecutionBoundary,
    GovernanceRequest,
    PolicyBundleRef,
    ProposedAction,
    ReceiptVerifier,
    TenantPolicyBinding,
)
from gove_zone.dag import (
    AuthorityGrant,
    AuthorityViolationError,
    DagReplayError,
    DagValidationError,
    EdgeKind,
    GovernanceDAG,
    GovernanceEdge,
    GovernanceNode,
    NodeKind,
    resolve_authority_grants,
    resolve_effective_scopes,
    validate_authority,
    verify_dag_replay,
)
from gove_zone.decision import (
    Decision,
    DecisionRecord,
    canonical_json,
    sha256_json,
)
from gove_zone.errors import (
    AuditError,
    AuthzDeniedError,
    ConsumptionLedgerError,
    DeniedError,
    EscalateError,
    GoveZoneError,
    IdentityError,
    IdentityRejectionReason,
    PolicyError,
    ProductionProfileError,
    ReceiptAlreadyUsedError,
    ReceiptRejectionReason,
    ReceiptValidationError,
    SigningError,
    UnknownToolError,
)
from gove_zone.escalation import (
    PendingApproval,
    approve_escalation,
    resume_with_receipt,
)
from gove_zone.evaluation import (
    EvaluationReport,
    EvaluationResult,
    EvaluationScenario,
    evaluate_policy_scenarios,
    load_evaluation_scenarios,
    load_evaluation_suite,
)
from gove_zone.executor import (
    GovernedExecutor,
    execute_with_receipt,
)
from gove_zone.frontend_contract import (
    receipt_to_governed_action,
    record_to_governed_action,
)
from gove_zone.gateway import (
    BypassAttemptError,
    GatewayResult,
    ScopedDecisionReceiptConfig,
    SealedTool,
    UniversalGateway,
    http_json_tool,
)
from gove_zone.identity import (
    Credential,
    CredentialType,
    IdentityProviderAdapter,
    MockAzureADAdapter,
    MockGoogleWorkspaceAdapter,
    MockIdentityProvider,
    MockOktaAdapter,
    Principal,
    PrincipalType,
    RBACMapper,
    RoleDefinition,
    govern_identity_action,
)
from gove_zone.integration import (
    GateMode,
    GateModeError,
    emit_receipt_for_hook,
    emit_receipts_for_hook,
    make_langgraph_tool_node,
    tool_call_from_hook_payload,
    tool_calls_from_hook_payload,
)
from gove_zone.kernel import Kernel
from gove_zone.mcp import mcp_tools_call, mcp_tools_list
from gove_zone.plan import WorkflowAuthorization
from gove_zone.policy import (
    AllowAllPolicy,
    BoundaryPolicy,
    CompositePolicy,
    DenyAllPolicy,
    PathBoundaryPolicy,
    Policy,
    PolicyRule,
    RiskTier,
    RiskTierPolicy,
    RuleSetPolicy,
    new_event_id,
)
from gove_zone.policy_sync import (
    AtomicJsonPolicyCache,
    ManagedPolicyProvenance,
    PolicySyncClient,
    PolicySyncError,
    PolicySyncScope,
    PolicySyncSnapshot,
    SyncedRuleSetPolicy,
    verify_policy_sync_snapshot,
)
from gove_zone.profile import GovernanceProfile
from gove_zone.receipt import DecisionReceipt, Receipt, Validator, safe_result_hash
from gove_zone.rejection import (
    alternative_from_record,
    discover_alternatives,
    rejection_dict,
)
from gove_zone.replay import (
    ReplayResult,
    find_event,
    replay_bundle,
    replay_call,
    replay_event,
    replay_from_side_store,
)
from gove_zone.replay_store import ReplaySideStore
from gove_zone.revocation import RevocationList, RevocationListError
from gove_zone.runtime_identity import (
    AtomicJsonRuntimeIdentityStore,
    GateScope,
    InMemoryEd25519WorkloadKeyProvider,
    LocalDevelopmentFileWorkloadKeyProvider,
    RuntimeEnrollmentClient,
    RuntimeHttpRequest,
    RuntimeHttpResponse,
    RuntimeIdentityDescriptor,
    RuntimeIdentityError,
    SignedRequestClient,
    WorkloadKeyProvider,
    b64url_decode,
    b64url_encode,
    canonical_enrollment_request_bytes,
    canonical_signed_runtime_request_bytes,
    public_key_thumbprint,
    sha256_bytes,
    sha256_text,
    verify_enrollment_pop,
    verify_signed_runtime_request,
)
from gove_zone.sandbox import (
    E2BSandbox,
    LocalProcessSandbox,
    SandboxError,
    SandboxProvider,
)
from gove_zone.signing import (
    Ed25519Signer,
    NullSigner,
    ReceiptSigner,
    make_signer,
)
from gove_zone.smoke import run_smoke
from gove_zone.tenant import (
    TenantPolicyStore,
    TransformPolicy,
    evaluate_tenant_action,
)
from gove_zone.tool import ToolCall, ToolRegistry, normalize_path_context
from gove_zone.trust import (
    DECISION_RECEIPT_PURPOSE,
    RECEIPT_V1,
    RECEIPT_V2,
    ReceiptTrustRegistry,
    ReceiptTrustScope,
    StaticReceiptTrustRegistry,
    TrustConfigurationError,
    TrustedReceiptKey,
    TrustReadinessIssue,
    TrustReadinessReport,
)
from gove_zone.verifier import (
    SCHEMA_VERSION,
    ProofPackRejectionReason,
    ProofPackVerificationResult,
    verify_proof_pack,
)
from gove_zone.workflow import (
    WorkflowDAG,
    WorkflowExecutor,
    WorkflowStep,
    WorkflowStepReceipt,
    verify_workflow_replay,
)
from gove_zone.yaml_policy import YAMLPolicy, YAMLRiskTierPolicy

# Single source of truth is the quoted literal below: hatch extracts it at
# build time ([tool.hatch.version] pattern in pyproject.toml), so installed
# metadata always mirrors it. importlib is preferred at runtime only to read
# the installed distribution's copy; the literal serves source/editable runs.
try:
    __version__ = _metadata.version("gove-zone")
except _metadata.PackageNotFoundError:  # pragma: no cover - source/editable runs
    __version__ = "1.0.0rc1"

__all__ = [
    "GENESIS_HASH",
    "AllowAllPolicy",
    "AuditChainError",
    "AuditError",
    "AuditEvent",
    "BoundaryPolicy",
    "AuthzDeniedError",
    "AuthzReason",
    "AuthzRegistryError",
    "AtomicJsonRuntimeIdentityStore",
    "AtomicJsonPolicyCache",
    "ChainHashAuditStore",
    "AuthorityGrant",
    "AuthorityViolationError",
    "DagReplayError",
    "DagValidationError",
    "EdgeKind",
    "GovernanceDAG",
    "GovernanceEdge",
    "GovernanceNode",
    "NodeKind",
    "PrincipalEntry",
    "PrincipalRegistry",
    "RECEIPT_V1",
    "RECEIPT_V2",
    "RevocationList",
    "RevocationListError",
    "authz_enforce_from_env",
    "CompositePolicy",
    "ConsumptionLedgerError",
    "Credential",
    "CredentialType",
    "Decision",
    "DecisionRecord",
    "DecisionReceipt",
    "DECISION_RECEIPT_PURPOSE",
    "DeniedError",
    "EvaluationReport",
    "EvaluationResult",
    "EvaluationScenario",
    "DenyAllPolicy",
    "Ed25519Signer",
    "EscalateError",
    "ExecutionBoundary",
    "BypassAttemptError",
    "GateScope",
    "GateMode",
    "GateModeError",
    "GatewayResult",
    "ScopedDecisionReceiptConfig",
    "GovernanceProfile",
    "SealedTool",
    "UniversalGateway",
    "http_json_tool",
    "GovernanceRequest",
    "GovernedExecutor",
    "GoveZoneError",
    "IdentityError",
    "IdentityProviderAdapter",
    "IdentityRejectionReason",
    "InMemoryEd25519WorkloadKeyProvider",
    "Kernel",
    "LocalDevelopmentFileWorkloadKeyProvider",
    "ManagedAgent",
    "MockAzureADAdapter",
    "MockGoogleWorkspaceAdapter",
    "MockIdentityProvider",
    "MockOktaAdapter",
    "SandboxProvider",
    "LocalProcessSandbox",
    "E2BSandbox",
    "SandboxError",
    "YAMLPolicy",
    "NullSigner",
    "PathBoundaryPolicy",
    "PendingApproval",
    "Policy",
    "PolicyBundleRef",
    "PolicyRule",
    "PolicyError",
    "PolicySyncClient",
    "PolicySyncError",
    "PolicySyncScope",
    "PolicySyncSnapshot",
    "ManagedPolicyProvenance",
    "ProductionProfileError",
    "ProofPackRejectionReason",
    "ProofPackVerificationResult",
    "Principal",
    "PrincipalType",
    "ProposedAction",
    "RBACMapper",
    "Receipt",
    "ReceiptAlreadyUsedError",
    "ReceiptTrustRegistry",
    "ReceiptTrustScope",
    "RiskTier",
    "RiskTierPolicy",
    "YAMLRiskTierPolicy",
    "LedgerObservability",
    "ReceiptConsumptionLedger",
    "ReceiptRejectionReason",
    "ReceiptSigner",
    "ReceiptValidationError",
    "ReceiptVerifier",
    "ReplayResult",
    "ReplaySideStore",
    "RoleDefinition",
    "RuleSetPolicy",
    "RuntimeEnrollmentClient",
    "RuntimeHttpRequest",
    "RuntimeHttpResponse",
    "RuntimeIdentityDescriptor",
    "RuntimeIdentityError",
    "SCHEMA_VERSION",
    "SigningError",
    "SignedRequestClient",
    "StaticReceiptTrustRegistry",
    "SyncedRuleSetPolicy",
    "TenantPolicyBinding",
    "TenantPolicyStore",
    "TransformPolicy",
    "ToolCall",
    "ToolRegistry",
    "TrustConfigurationError",
    "TrustedReceiptKey",
    "TrustReadinessIssue",
    "TrustReadinessReport",
    "UnknownToolError",
    "Validator",
    "WorkflowAuthorization",
    "WorkloadKeyProvider",
    "WorkflowDAG",
    "WorkflowExecutor",
    "WorkflowStep",
    "WorkflowStepReceipt",
    "__version__",
    "agentdojo_scenarios_from_fixture",
    "alternative_from_record",
    "approve_escalation",
    "discover_alternatives",
    "emit_receipt_for_hook",
    "emit_receipts_for_hook",
    "evaluate_policy_scenarios",
    "evaluate_tenant_action",
    "execute_with_receipt",
    "injecagent_scenarios_from_fixture",
    "load_benchmark_suite",
    "load_evaluation_scenarios",
    "load_evaluation_suite",
    "make_langgraph_tool_node",
    "b64url_decode",
    "b64url_encode",
    "canonical_enrollment_request_bytes",
    "canonical_json",
    "canonical_signed_runtime_request_bytes",
    "find_event",
    "govern_identity_action",
    "make_signer",
    "mcp_tools_call",
    "mcp_tools_list",
    "new_event_id",
    "normalize_path_context",
    "public_key_thumbprint",
    "receipt_to_governed_action",
    "record_to_governed_action",
    "rejection_dict",
    "replay_bundle",
    "replay_call",
    "replay_event",
    "replay_from_side_store",
    "resolve_authority_grants",
    "resolve_effective_scopes",
    "resume_with_receipt",
    "run_smoke",
    "safe_result_hash",
    "sha256_bytes",
    "sha256_json",
    "sha256_text",
    "tool_call_from_hook_payload",
    "tool_calls_from_hook_payload",
    "validate_authority",
    "verify_dag_replay",
    "verify_enrollment_pop",
    "verify_proof_pack",
    "verify_policy_sync_snapshot",
    "verify_signed_runtime_request",
    "verify_workflow_replay",
]
