"""ACGS Proof Pack: enterprise evidence bundle for one governed action.

A **proof pack** is a portable, self-describing directory of evidence that one
governed action was policy-checked before execution and that the record of that
check is intact. It is built for three audiences at once:

- **engineers** get machine-readable JSON artifacts plus a one-command verify;
- **auditors** get a per-file integrity manifest (``evidence.json``) and a
  human-readable ``verification-summary.md`` stating exactly what is and is
  not proven;
- **regulators** get a plain-language summary section with no jargon.

Layout (schema ``acgs/proof-pack/v1.1``; ``acgs/proof-pack/v1`` packs remain
verifiable — see ``_SUMMARY_REVISION_FOR_SCHEMA``)::

    proofpack/
    ├── evidence.json             # manifest: action, actor, policy, sha256 digests
    ├── decision-receipt.json     # the Decision Receipt, verbatim
    ├── audit-chain.json          # the hash-linked audit events (chain order)
    ├── replay-report.json        # decision re-derivation result (or not_available)
    └── verification-summary.md   # human-readable summary for auditors/regulators

Relationship to the conformance pack (``gove-zone proofpack``) and the offline
verifier (:mod:`acgs_proofpack_verifier.verifier`): this module packages the evidence of a
*specific* governed action, while the conformance pack demonstrates the gate
matrix. Verification here **reuses** :func:`acgs_proofpack_verifier.verifier.verify_proof_pack`
verbatim — the pack is materialised into the ``gove-zone/proof-pack/v1`` shape
in a temporary directory and handed to the existing hardened verifier, so there
is exactly one receipt/chain verification code path in the codebase.

Independence (mirrors verifier.py §5.4): module-scope imports are restricted to
the receipt/verify surface. The decision-replay tier needs the policy engine;
those imports are **lazy**, performed only when replay material is supplied.
A static AST guard test pins this boundary.

Fail-closed: :func:`verify_pack` never raises — every failure path resolves to
``valid=False`` with a stable reason code. :func:`generate_proof_pack` refuses
to mint an evidence bundle from inconsistent inputs (broken chain, unanchored
or binding-broken receipt, failed replay): an evidence bundle that contradicts
itself is worse than none.

Leak-safety: the pack carries the receipt, the audit events, and a replay
*report* — never the raw arguments or the replay side store. Re-deriving the
decisions requires the relying party to supply the policy bundle and side
store out-of-band at verify time.
"""

from __future__ import annotations

import hashlib
import json
import tempfile
from dataclasses import dataclass, field
from enum import StrEnum
from pathlib import Path
from typing import TYPE_CHECKING, Any

from acgs_proofpack_verifier.audit import GENESIS_HASH, ChainHashAuditStore
from acgs_proofpack_verifier.receipt import DecisionReceipt
from acgs_proofpack_verifier.verifier import (
    SCHEMA_VERSION as INNER_SCHEMA_VERSION,
)
from acgs_proofpack_verifier.verifier import (
    ProofPackVerificationResult,
    verify_proof_pack,
)

if TYPE_CHECKING:
    from acgs_proofpack_verifier.revocation import RevocationList

# The schema version newly generated packs declare. Every supported schema
# version is bound 1:1 to a summary-template revision (see
# _SUMMARY_REVISION_FOR_SCHEMA): auditor-wording changes ship as a NEW schema
# version instead of changing already-issued bytes in place, so a verifier
# installed before a wording change rejects newer packs with
# SCHEMA_VERSION_UNSUPPORTED (an upgrade signal) rather than
# SUMMARY_BINDING_MISMATCH (a false tamper alarm).
PACK_SCHEMA_VERSION = "acgs/proof-pack/v1.1"
GENERATED_WITH = "acgs proofpack generate (acgs_proofpack_verifier.proofpack)"

# The exact generator-identity footers this verifier accepts after the summary's
# final ``\n---\n`` separator. The footer is excised from the tamper-evident
# byte-compare (it is an unauthenticated attestation — see verify_pack), but the
# excised suffix must still be EXACTLY one known footer line: anything else
# (appended Markdown, a second paragraph, a reworded line) fails verification,
# so the excision cannot be used to smuggle arbitrary auditor-facing prose past
# the summary byte-compare.
_KNOWN_GENERATOR_FOOTERS = frozenset(
    f"Generated by `acgs proofpack generate ({module})`.\n"
    for module in ("gove_zone.proofpack", "acgs_proofpack_verifier.proofpack")
)

EVIDENCE_FILE = "evidence.json"
RECEIPT_FILE = "decision-receipt.json"
AUDIT_CHAIN_FILE = "audit-chain.json"
REPLAY_REPORT_FILE = "replay-report.json"
SUMMARY_FILE = "verification-summary.md"

# The artifacts whose digests evidence.json binds. evidence.json cannot contain
# its own digest (self-reference), so it is the manifest, not a member.
ARTIFACT_FILES = (RECEIPT_FILE, AUDIT_CHAIN_FILE, REPLAY_REPORT_FILE, SUMMARY_FILE)

# Decisions whose receipts self-validate as executable ("accept" verdicts in the
# offline verifier's vocabulary). DENY/ESCALATE receipts are evidence of a block,
# and verify() raises on them by design — they are declared "reject".
_ACCEPT_DECISIONS = frozenset({"allow", "transform"})

# Fail-closed constitution-hash registry cross-check reason strings (G2.5). The
# taxonomy is ported verbatim from the proven ``acgs_governance_eval_mvp``
# reference so the behaviour matches; the cross-check runs ONLY when the caller
# supplies a registry (additive / v1-safe — no registry => carried, not checked).
CONSTITUTION_HASH_MISSING = "constitution_hash_missing"
CONSTITUTION_HASH_NOT_IN_REGISTRY = "constitution_hash_not_in_registry"
CONSTITUTION_REGISTRY_MALFORMED = "constitution_registry_malformed"
CONSTITUTION_REGISTRY_UNREADABLE = "constitution_registry_unreadable"

_HEX = frozenset("0123456789abcdef")


class PackGenerationError(Exception):
    """Raised when the inputs cannot honestly be packaged as evidence."""


class PackRejectionReason(StrEnum):
    """Stable, machine-readable pack-level failure codes.

    Failures found by the inner receipt/chain verifier surface their own codes
    verbatim (see :class:`acgs_proofpack_verifier.verifier.ProofPackRejectionReason` and
    :class:`acgs_proofpack_verifier.errors.ReceiptRejectionReason`); these cover the ACGS
    pack envelope (evidence manifest, artifact integrity, cross-binding,
    replay re-derivation).
    """

    PACK_NOT_FOUND = "PACK_NOT_FOUND"
    EVIDENCE_MISSING = "EVIDENCE_MISSING"
    EVIDENCE_MALFORMED = "EVIDENCE_MALFORMED"
    SCHEMA_VERSION_MISSING = "SCHEMA_VERSION_MISSING"
    SCHEMA_VERSION_UNSUPPORTED = "SCHEMA_VERSION_UNSUPPORTED"
    SCHEMA_VERSION_MISMATCH = "SCHEMA_VERSION_MISMATCH"
    ARTIFACT_MISSING = "ARTIFACT_MISSING"
    ARTIFACT_DIGEST_MISMATCH = "ARTIFACT_DIGEST_MISMATCH"
    RECEIPT_BINDING_MISMATCH = "RECEIPT_BINDING_MISMATCH"
    EVIDENCE_BINDING_MISMATCH = "EVIDENCE_BINDING_MISMATCH"
    SUMMARY_BINDING_MISMATCH = "SUMMARY_BINDING_MISMATCH"
    AUDIT_CHAIN_MALFORMED = "AUDIT_CHAIN_MALFORMED"
    AUDIT_BINDING_MISMATCH = "AUDIT_BINDING_MISMATCH"
    REPLAY_REPORT_MALFORMED = "REPLAY_REPORT_MALFORMED"
    REPLAY_MATERIAL_MALFORMED = "REPLAY_MATERIAL_MALFORMED"
    REPLAY_MISMATCH = "REPLAY_MISMATCH"
    VERIFIER_ERROR = "VERIFIER_ERROR"


@dataclass(frozen=True)
class PackVerificationResult:
    """Structured, fail-closed verification verdict for one ACGS proof pack.

    ``valid`` is the single gate a relying party keys on. ``integrity_status``
    is the artifact-digest verdict (``intact`` / ``tampered`` / ``incomplete``).
    ``receipt_and_chain`` is the untouched inner verdict from
    :func:`acgs_proofpack_verifier.verifier.verify_proof_pack`. ``replay_status`` is one of
    ``recorded`` (a generate-time report is present but not re-derived),
    ``reverified`` (re-derived now from out-of-band material), ``failed``,
    or ``not_available``.
    """

    valid: bool
    schema_version: str | None
    integrity_status: str  # "intact" | "tampered" | "incomplete" | "unknown"
    receipt_and_chain: ProofPackVerificationResult | None
    replay_status: str
    reasons: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "valid": self.valid,
            "schema_version": self.schema_version,
            "integrity_status": self.integrity_status,
            "receipt_and_chain": (
                self.receipt_and_chain.to_dict() if self.receipt_and_chain else None
            ),
            "replay_status": self.replay_status,
            "reasons": list(self.reasons),
        }


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _dump_json(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _declared_verdict(receipt: DecisionReceipt) -> str:
    return "accept" if receipt.decision in _ACCEPT_DECISIONS else "reject"


def _receipt_evidence_sections(receipt: DecisionReceipt) -> dict[str, dict[str, Any]]:
    """The evidence.json sections that are DERIVED from the receipt.

    Single source of truth for both generation (these sections are written into
    ``evidence.json``) and verification (tier 3 re-derives them from the
    hash-protected receipt and requires strict equality). ``evidence.json``
    cannot carry its own digest, so every receipt-derived claim it makes must be
    re-checkable against the receipt — this helper is what makes a forged
    ``governed_action`` / ``actor`` / ``policy`` section detectable.
    """
    return {
        "governed_action": {
            "proposed_action": receipt.proposed_action,
            "declared_goal": receipt.declared_goal,
            "execution_boundary": receipt.execution_boundary,
            "decision": receipt.decision,
            "matched_rules": list(receipt.matched_rules),
        },
        "actor": {
            "id": receipt.actor,
            "tenant_id": receipt.tenant_id,
            "authority": receipt.authority,
            "validator_id": receipt.validator_id,
            "validator_role": receipt.validator_role,
        },
        "policy": {
            "bundle_id": receipt.policy_bundle_id,
            "version": receipt.policy_version,
            "hash": receipt.policy_hash,
        },
        "receipt": {
            "receipt_id": receipt.receipt_id,
            "request_id": receipt.request_id,
            "receipt_hash": receipt.receipt_hash,
            "audit_event_hash": receipt.audit_event_hash,
            "signature_algorithm": receipt.signature_algorithm,
            "signing_key_id": receipt.signing_key_id,
        },
    }


# --- generation ---------------------------------------------------------------


def _run_replay(audit_path: Path, policy_bundle: Path, side_store: Path) -> dict[str, Any]:
    """Re-derive every decision in the chain.

    The optional decision-replay tier re-runs the policy engine and therefore
    depends on the full ``gove-zone`` runtime (policy/replay/replay_store),
    which this dependency-minimal verifier intentionally does NOT vendor. The
    offline integrity + receipt + audit-chain tiers never reach this code; a
    caller that supplies out-of-band replay material gets a clean fail-closed
    error (``REPLAY_MATERIAL_MALFORMED``) via the wrapping handler, never a
    silent accept.
    """
    raise ModuleNotFoundError(
        "decision-replay re-derivation requires the full gove-zone engine; "
        "it is not available in the dependency-minimal acgs-proofpack-verifier"
    )


def generate_proof_pack(
    out_dir: str | Path,
    *,
    receipt_path: str | Path,
    audit_path: str | Path,
    policy_bundle: str | Path | None = None,
    side_store: str | Path | None = None,
    now_iso: str | None = None,
    force: bool = False,
) -> dict[str, Any]:
    """Generate an ACGS proof pack for one governed action.

    Args:
        out_dir: directory to create (must not already contain a pack unless
            ``force``).
        receipt_path: the governed action's Decision Receipt JSON.
        audit_path: the audit chain JSONL the receipt is anchored in.
        policy_bundle: optional RuleSetPolicy bundle JSON. Together with
            ``side_store`` it enables the decision-replay tier.
        side_store: optional replay side store JSONL (raw retained arguments).
        now_iso: injected generation timestamp for deterministic output;
            defaults to the wall clock.
        force: overwrite pack files already present in ``out_dir``.

    Returns:
        A summary dict: ``{"status": "pass", "output_directory": ..., "files",
        "preflight"}``.

    Raises:
        PackGenerationError: when the inputs are inconsistent — broken chain,
            malformed or unanchored receipt, broken receipt-hash binding, or a
            failed replay. Fail-closed: an evidence bundle is only minted from
            inputs that actually cohere.
    """
    receipt_path = Path(receipt_path)
    audit_path = Path(audit_path)
    out = Path(out_dir)

    if (policy_bundle is None) != (side_store is None):
        raise PackGenerationError("replay material requires BOTH --policy-bundle and --side-store")

    # --- pre-flight: refuse to package evidence that contradicts itself -------
    try:
        receipt = DecisionReceipt.from_json(receipt_path.read_text(encoding="utf-8"))
    except (OSError, ValueError, KeyError, TypeError) as exc:
        raise PackGenerationError(f"cannot load receipt {receipt_path}: {exc}") from exc

    if not receipt.receipt_hash or receipt.compute_hash() != receipt.receipt_hash:
        raise PackGenerationError(
            "receipt_hash binding is broken: the receipt's bound fields do not "
            "re-hash to receipt_hash — refusing to package tampered input"
        )

    store = ChainHashAuditStore(audit_path)
    try:
        chain = store.verify_chain()
        events = list(store.iter_events())
    except Exception as exc:  # noqa: BLE001 — unreadable chain must not become evidence
        raise PackGenerationError(f"cannot read audit chain {audit_path}: {exc}") from exc
    if not chain["valid"]:
        raise PackGenerationError(
            f"audit chain fails verification ({len(chain['failures'])} failure(s)) — "
            "refusing to package a broken chain as evidence"
        )
    event_hashes = {e.get("event_hash") for e in events}
    if receipt.audit_event_hash not in event_hashes:
        raise PackGenerationError(
            "receipt is not anchored in the supplied audit chain "
            "(audit_event_hash not found) — refusing to package unanchored evidence"
        )

    replay_report: dict[str, Any]
    if policy_bundle is not None and side_store is not None:
        try:
            replay_result = _run_replay(audit_path, Path(policy_bundle), Path(side_store))
        except Exception as exc:  # noqa: BLE001 — malformed replay material is a refusal
            raise PackGenerationError(f"cannot run decision replay: {exc}") from exc
        if not replay_result.get("valid"):
            raise PackGenerationError(
                "decision replay FAILED: the re-derived decisions do not match the "
                "recorded chain — refusing to package contradictory evidence"
            )
        replay_report = {
            "schema_version": PACK_SCHEMA_VERSION,
            "status": "verified",
            "note": (
                "Every decision in the audit chain was re-derived from the retained "
                "raw arguments at generation time and byte-matched the recorded "
                "decision. Re-derivation at verify time requires the policy bundle "
                "and side store, supplied out-of-band (they are not in this pack)."
            ),
            "result": replay_result,
        }
    else:
        replay_report = {
            "schema_version": PACK_SCHEMA_VERSION,
            "status": "not_available",
            "note": (
                "No replay material (policy bundle + side store) was supplied at "
                "generation time, so decisions were not re-derived. Receipt and "
                "audit-chain integrity are still fully verifiable offline."
            ),
            "result": None,
        }

    # --- write the pack --------------------------------------------------------
    out.mkdir(parents=True, exist_ok=True)
    if not force:
        existing = [n for n in (EVIDENCE_FILE, *ARTIFACT_FILES) if (out / n).exists()]
        if existing:
            raise PackGenerationError(
                f"refusing to overwrite existing pack files in {out}: "
                f"{', '.join(existing)} (pass force=True / --force)"
            )

    from datetime import UTC, datetime

    if now_iso is None:
        now_iso = datetime.now(UTC).isoformat()
    else:
        try:
            datetime.fromisoformat(now_iso)
        except ValueError as exc:
            raise PackGenerationError(
                f"--now-iso is not a valid ISO-8601 timestamp: {exc}"
            ) from exc

    (out / RECEIPT_FILE).write_text(receipt.to_json() + "\n", encoding="utf-8")

    _dump_json(
        out / AUDIT_CHAIN_FILE,
        {
            "schema_version": PACK_SCHEMA_VERSION,
            "genesis_hash": GENESIS_HASH,
            "event_count": len(events),
            "last_hash": chain["last_hash"],
            "events": events,
        },
    )

    _dump_json(out / REPLAY_REPORT_FILE, replay_report)

    (out / SUMMARY_FILE).write_text(
        _render_summary(
            receipt=receipt,
            chain=chain,
            event_count=len(events),
            replay_report=replay_report,
            now_iso=now_iso,
        ),
        encoding="utf-8",
    )

    artifacts = {
        name: {
            "sha256": _sha256_file(out / name),
            "bytes": (out / name).stat().st_size,
        }
        for name in ARTIFACT_FILES
    }
    evidence = {
        "schema_version": PACK_SCHEMA_VERSION,
        "generated_at": now_iso,
        "generated_with": GENERATED_WITH,
        **_receipt_evidence_sections(receipt),
        "audit": {
            "event_count": len(events),
            "last_hash": chain["last_hash"],
        },
        "artifacts": artifacts,
        "how_to_verify": "acgs proofpack verify <pack-dir> [--verifier-key <pubkey>]",
    }
    _dump_json(out / EVIDENCE_FILE, evidence)

    return {
        "status": "pass",
        "output_directory": str(out),
        "files": [EVIDENCE_FILE, *ARTIFACT_FILES],
        "preflight": {
            "receipt_binding_intact": True,
            "audit_chain_valid": True,
            "receipt_anchored": True,
            "replay": replay_report["status"],
        },
    }


# --- human-readable summary -----------------------------------------------------

# Auditor-prose revisions of the summary template, bound 1:1 to pack schema
# versions. The summary body is byte-compared at verify time: generation
# renders the revision bound to PACK_SCHEMA_VERSION, and verification
# re-renders EXACTLY the revision bound to the pack's DECLARED schema_version
# — never a set of alternatives. A wording change therefore ships as a new
# schema version instead of changing already-issued bytes in place:
#
# * packs issued under an older schema keep verifying under that schema;
# * verifiers installed before the change reject newer packs with
#   SCHEMA_VERSION_UNSUPPORTED (an upgrade signal, not a tamper verdict);
# * a current pack whose summary is swapped for an older revision's rendering
#   fails SUMMARY_BINDING_MISMATCH — there is no cross-revision acceptance a
#   downgrade could exploit to reinstate superseded auditor wording;
# * a pack whose artifacts disagree about the declared schema version fails
#   SCHEMA_VERSION_MISMATCH: downgrading evidence.json plus the summary alone
#   (recomputing the unauthenticated digests) is caught because
#   audit-chain.json and replay-report.json still declare the newer version.
#
# Residual limit: schema_version is an unauthenticated envelope declaration,
# for SIGNED packs too. The only signed artifact in a pack is the receipt: its
# Ed25519 signature covers the receipt's bound fields (and, through
# audit_event_hash, the chain prefix it anchors to), never evidence.json,
# audit-chain.json, replay-report.json, or the summary. An editor who rewrites
# those envelope artifacts self-consistently under an older SUPPORTED schema,
# leaving the signed receipt untouched, produces a pack that verifies with
# signature_verified=True (the signature verdict attests the receipt, not the
# envelope) and is indistinguishable from what the still-supported older
# generator legitimately emits for the same receipt: pack generation is
# deliberately key-free, so anyone holding a receipt + chain can mint a pack
# under any supported schema version without forging anything. Binding the
# pack schema/template revision into a signed artifact would require a
# generation-time pack-level signature, a format change v1/v1.1 do not have;
# an opt-in one could not close the gap, since a downgrader strips optional
# artifacts along with the version. What the revision binding above
# guarantees is narrower: the summary prose is EXACTLY the trusted template
# revision bound to the declared schema_version (all accepted revisions are
# generator-authored, byte-pinned templates differing only in auditor
# wording), and the pack presents itself under that older, superseded
# schema_version instead of passing as current evidence.
#
# Revisions differ ONLY in auditor wording — every substantive fact (receipt,
# chain, replay, signature posture) is identical across revisions.
_SUMMARY_REVISION_FOR_SCHEMA = {
    "acgs/proof-pack/v1": 1,
    "acgs/proof-pack/v1.1": 2,
}

# Revision 1 overstated the byte-compare ("a rewritten summary ... fails")
# without the body/footer distinction; revision 2 scopes the claim to the
# summary body, limits the re-derivation claim to receipt/chain-derived prose
# (the interpolated generation timestamp and replay-status wording follow the
# pack's own unauthenticated attestations), names the generator footer as an
# unauthenticated attestation, and scopes the byte-compare guarantee to
# internal consistency: every hash in an unsigned pack is an unkeyed SHA-256
# an editor can recompute, so a self-consistent whole-pack rewrite still
# verifies, and only a trusted signature check authenticates the records
# themselves. Historical packs carry revision 1 verbatim — these blocks are
# frozen bytes, never reworded retroactively.
_SUMMARY_PROVES_ITEM_3 = {
    1: """3. `evidence.json`'s action / actor / policy sections and this summary are
   re-derived from the hash-bound receipt and chain at verify time — a
   rewritten summary or evidence file fails verification even if every file
   digest is recomputed to match.""",
    2: """3. `evidence.json`'s action / actor / policy sections and this summary's body
   (everything above the trailing generator footer) are re-rendered and
   byte-compared at verify time, so the pack is internally consistent:
   receipt- and chain-derived prose cannot be edited in place, without also
   rewriting the records it is derived from, even if every file digest is
   recomputed to match. Whether those records are themselves as originally
   issued is a separate question, settled only by verifying a signed receipt
   against a trusted key (see the unsigned-pack caveats below). The body's
   generation timestamp and replay-status wording are rendered from the
   pack's own recorded attestations (`evidence.json`, `replay-report.json`),
   so they are exactly as trustworthy as those attestations.""",
}
_SUMMARY_FOOTER_ATTESTATION_BULLET = {
    1: "",
    2: """
- For an UNSIGNED pack, that the records were not rewritten wholesale. Every
  integrity value in this pack (`receipt_hash`, the audit-chain hashes, the
  artifact digests) is an unkeyed SHA-256 an editor can recompute, so a
  forger who rewrites the receipt, chain, evidence and summary together,
  self-consistently, produces a pack that still verifies. Unsigned
  verification detects inconsistent edits only; it does not authenticate the
  records. A signed receipt, checked against an independently obtained public
  key, closes this for the receipt's bound fields.
- Which tool generated this pack. The trailing "Generated by ..." footer (and
  `generated_with` in `evidence.json`) is an unauthenticated generator
  attestation: it is not derived from the hash-bound receipt or chain, and
  offline verification accepts any known generator identity in its place, so
  it must not be read as authenticated provenance.""",
}


def _render_summary(
    *,
    receipt: DecisionReceipt,
    chain: dict[str, Any],
    event_count: int,
    replay_report: dict[str, Any],
    now_iso: str,
    schema_version: str = PACK_SCHEMA_VERSION,
) -> str:
    revision = _SUMMARY_REVISION_FOR_SCHEMA[schema_version]
    signed = receipt.signature_algorithm != "none"
    decision = receipt.decision.upper()
    decision_line = (
        f"**{decision}** (executable)"
        if receipt.decision in _ACCEPT_DECISIONS
        else (
            f"**{decision}** (blocked — this receipt proves the action was NOT "
            "allowed to run as requested)"
        )
    )
    chain_line = f"{'PASS' if chain['valid'] else 'FAIL'} ({event_count} event(s), hash-linked)"
    replay_status = replay_report["status"]
    replay_line = {
        "verified": (
            "PASS (generator attestation) — every recorded decision was re-derived "
            "from retained raw arguments at generation time and matched the audit "
            "chain byte-for-byte. Re-derive independently at verify time with "
            "`--policy-bundle`/`--side-store`."
        ),
        "not_available": (
            "NOT AVAILABLE — no replay material was supplied at generation time; "
            "receipt and chain integrity remain independently verifiable."
        ),
    }[replay_status]
    signature_line = (
        f"signed ({receipt.signature_algorithm}, key `{receipt.signing_key_id}`) — "
        "verification requires the relying party's own copy of the public key "
        "(`--verifier-key`), never a key shipped inside this pack"
        if signed
        else (
            "UNSIGNED (development posture) — the receipt is tamper-evident via "
            "`receipt_hash` but carries no cryptographic signature; do not treat "
            "an unsigned pack as production evidence"
        )
    )

    return f"""# ACGS Proof Pack — Verification Summary

Generated: {now_iso}
Schema: `{schema_version}`

## What this pack is

This directory is a self-contained evidence bundle for **one governed action**.
It documents that the action was checked against policy **before** execution,
what the decision was, and that the record of that decision is intact. It can
be verified offline, without access to the system that produced it, with:

```
acgs proofpack verify <this-directory>
```

## Outcome at a glance

| Check | Result |
|---|---|
| Governance decision | {decision_line} |
| Receipt integrity (`receipt_hash` binding) | PASS at generation time |
| Audit chain integrity | {chain_line} |
| Receipt anchored in audit chain | PASS at generation time |
| Decision replay (re-derivation) | {replay_line} |
| Signature | {signature_line} |

## The governed action

- **Action**: `{receipt.proposed_action}`
- **Declared goal**: {receipt.declared_goal or "(none declared)"}
- **Actor**: `{receipt.actor}` (tenant `{receipt.tenant_id}`)
- **Authority**: {receipt.authority or "(none recorded)"}
- **Execution boundary**: `{receipt.execution_boundary}`
- **Policy**: `{receipt.policy_bundle_id}` version `{receipt.policy_version}`
  (hash `{receipt.policy_hash}`)
- **Receipt**: `{receipt.receipt_id}` (request `{receipt.request_id}`)

## For engineers

- `decision-receipt.json` — the Decision Receipt. Its `receipt_hash` is a
  SHA-256 over the canonical JSON of every bound field (actor, action,
  argument hash, policy hash, decision, authority, ...). Change any field and
  the hash no longer matches.
- `audit-chain.json` — the audit events in chain order. Each event's
  `event_hash` is SHA-256 over the event minus the hash itself, and each
  `previous_hash` links to the prior event, back to a 64-zero genesis hash.
- `replay-report.json` — whether decisions were re-derived from retained raw
  arguments at generation time. Raw arguments are **not** in this pack.
- `evidence.json` — SHA-256 digests of the other four files, plus the action /
  actor / policy summary. Verification recomputes the digests AND re-derives
  every receipt-derived field from the hash-protected receipt, so an edit to
  any artifact — or to evidence.json's own descriptive sections — is detected.

## For auditors

What a passing verification **proves**:

1. The Decision Receipt's bound fields are exactly as issued (hash binding).
2. The audit chain is internally consistent and the receipt is anchored to a
   specific event in it.
{_SUMMARY_PROVES_ITEM_3[revision]}

What it does **not** prove:

- That the chain was not truncated after the anchored event (supply an
  out-of-band last-hash anchor to close this).
- That the clock or identity claims inside the receipt are true — those are
  attestations of the issuing system.
- The generation timestamp and the replay report's "verified at generation
  time" status are generator attestations: a consistent forgery of those two
  fields is not detectable offline. Independent replay re-derivation requires
  the policy bundle and side store, supplied out-of-band at verify time.
- An unsigned pack does not prove **who** issued the receipt. Only a signed
  receipt, checked against a public key you obtained independently of this
  pack, proves issuer identity.{_SUMMARY_FOOTER_ATTESTATION_BULLET[revision]}

## For regulators (plain language)

Before this software action was carried out, an automated policy check decided
whether it was permitted. This bundle is the tamper-evident record of that
check: the decision itself (`{decision}`), the rule set used, who requested
it, and a cryptographic chain of log entries it belongs to. Anyone with this
folder and the free verification tool can re-check — without trusting the
operator — that none of these records were altered after the fact. It is the
software equivalent of a stamped, page-numbered logbook entry.

---
Generated by `{GENERATED_WITH}`.
"""


# --- verification ---------------------------------------------------------------


def _fail(
    reason: str,
    *,
    schema_version: str | None = None,
    integrity_status: str = "unknown",
) -> PackVerificationResult:
    return PackVerificationResult(
        valid=False,
        schema_version=schema_version,
        integrity_status=integrity_status,
        receipt_and_chain=None,
        replay_status="not_available",
        reasons=[reason],
    )


def verify_pack(
    pack_dir: str | Path,
    *,
    verifier: Any = None,
    require_signature: bool | None = None,
    now_iso: str | None = None,
    revoked_keys: RevocationList | None = None,
    policy_bundle: str | Path | None = None,
    side_store: str | Path | None = None,
    constitution_registry: str | Path | None = None,
) -> PackVerificationResult:
    """Verify an ACGS proof pack offline. Never raises; fail-closed.

    Verification tiers:

    1. **Integrity** — recompute the SHA-256 of every artifact and compare to
       ``evidence.json``. Any mismatch or missing file fails the pack.
    2. **Receipt + chain** — the receipt and audit events are materialised into
       the ``gove-zone/proof-pack/v1`` shape in a temporary directory and handed
       to :func:`acgs_proofpack_verifier.verifier.verify_proof_pack` (single verification code
       path; same signature posture, anchoring, and fail-closed semantics).
    3. **Cross-binding** — ``evidence.json``'s recorded receipt hash and chain
       tail must match the artifacts they describe.
    4. **Replay (optional)** — when ``policy_bundle`` and ``side_store`` are
       supplied out-of-band, every decision is re-derived now; a recorded
       generate-time replay report alone is never treated as re-verification.
    5. **Constitution registry (optional)** — when ``constitution_registry`` is
       supplied, the pack's stamped ``evidence.constitution.hash`` is looked up
       in that trusted registry and the pack fails closed if it is missing,
       absent, or the registry itself is malformed/unreadable (G2.5). With no
       registry the optional ``constitution`` block is carried but not checked,
       so pre-G2.5 packs remain valid (additive / v1-safe).

    Args mirror :func:`acgs_proofpack_verifier.verifier.verify_proof_pack` for the trust
    anchor (``verifier``, ``require_signature``, ``now_iso``, ``revoked_keys``).
    ``constitution_registry`` is the optional path to a JSON array of trusted
    64-hex constitution hashes for the tier-5 cross-check.
    """
    try:
        return _verify_pack_inner(
            Path(pack_dir),
            verifier=verifier,
            require_signature=require_signature,
            now_iso=now_iso,
            revoked_keys=revoked_keys,
            policy_bundle=policy_bundle,
            side_store=side_store,
            constitution_registry=constitution_registry,
        )
    except Exception:  # noqa: BLE001 — fail-closed: never let an exception become "accept".
        return _fail(PackRejectionReason.VERIFIER_ERROR)


def _verify_pack_inner(
    root: Path,
    *,
    verifier: Any,
    require_signature: bool | None,
    now_iso: str | None,
    revoked_keys: RevocationList | None,
    policy_bundle: str | Path | None,
    side_store: str | Path | None,
    constitution_registry: str | Path | None = None,
) -> PackVerificationResult:
    if not root.is_dir():
        return _fail(PackRejectionReason.PACK_NOT_FOUND)

    evidence_path = root / EVIDENCE_FILE
    if not evidence_path.is_file():
        return _fail(PackRejectionReason.EVIDENCE_MISSING)
    try:
        evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
        if not isinstance(evidence, dict):
            raise ValueError("evidence is not an object")
    except (ValueError, OSError):
        return _fail(PackRejectionReason.EVIDENCE_MALFORMED)

    schema_version = evidence.get("schema_version")
    if not schema_version:
        return _fail(PackRejectionReason.SCHEMA_VERSION_MISSING)
    if schema_version not in _SUMMARY_REVISION_FOR_SCHEMA:
        return _fail(PackRejectionReason.SCHEMA_VERSION_UNSUPPORTED, schema_version=schema_version)

    reasons: list[str] = []

    # Parse the replay report up front: tier 3 re-renders the summary from its
    # status and tier 4 reports it. A malformed report fails closed here.
    report_doc: dict[str, Any] | None = None
    report_path = root / REPLAY_REPORT_FILE
    if report_path.is_file():
        try:
            parsed = json.loads(report_path.read_text(encoding="utf-8"))
            if not isinstance(parsed, dict) or parsed.get("status") not in {
                "verified",
                "not_available",
            }:
                raise ValueError("unexpected replay report shape")
            report_doc = parsed
        except (ValueError, OSError):
            reasons.append(PackRejectionReason.REPLAY_REPORT_MALFORMED)

    # --- cross-artifact schema pinning ----------------------------------------
    # evidence.json's declared schema_version selects the summary-template
    # revision, so every OTHER artifact that declares a schema_version must
    # declare the SAME one. Without this, an editor could downgrade
    # evidence.json + the summary to an older schema (recomputing the
    # unauthenticated digests) while leaving audit-chain.json /
    # replay-report.json at the current version: a mixed-version pack whose
    # legacy summary rendering would pass the schema-bound byte-compare. The
    # audit chain's declared version is checked in tier 2, where it is parsed.
    if report_doc is not None and report_doc.get("schema_version") != schema_version:
        reasons.append(PackRejectionReason.SCHEMA_VERSION_MISMATCH)

    # --- tier 1: artifact integrity -----------------------------------------
    declared = evidence.get("artifacts")
    declared = declared if isinstance(declared, dict) else {}
    integrity_status = "intact"
    for name in ARTIFACT_FILES:
        entry = declared.get(name)
        expected = entry.get("sha256") if isinstance(entry, dict) else None
        path = root / name
        if not path.is_file() or not expected:
            integrity_status = "incomplete"
            if PackRejectionReason.ARTIFACT_MISSING not in reasons:
                reasons.append(PackRejectionReason.ARTIFACT_MISSING)
            continue
        if _sha256_file(path) != expected:
            if integrity_status != "incomplete":
                integrity_status = "tampered"
            if PackRejectionReason.ARTIFACT_DIGEST_MISMATCH not in reasons:
                reasons.append(PackRejectionReason.ARTIFACT_DIGEST_MISMATCH)

    # --- tier 2: receipt + chain via the existing hardened verifier ----------
    inner: ProofPackVerificationResult | None = None
    receipt_path = root / RECEIPT_FILE
    chain_path = root / AUDIT_CHAIN_FILE
    if receipt_path.is_file() and chain_path.is_file():
        try:
            receipt = DecisionReceipt.from_json(receipt_path.read_text(encoding="utf-8"))
            chain_doc = json.loads(chain_path.read_text(encoding="utf-8"))
            events = chain_doc["events"]
            if not isinstance(events, list) or not all(isinstance(e, dict) for e in events):
                raise ValueError("audit-chain.json events must be a list of objects")
        except (ValueError, KeyError, TypeError, OSError):
            reasons.append(PackRejectionReason.AUDIT_CHAIN_MALFORMED)
        else:
            with tempfile.TemporaryDirectory(prefix="acgs-proofpack-") as tmp:
                inner = _run_inner_verifier(
                    Path(tmp),
                    receipt=receipt,
                    events=events,
                    verifier=verifier,
                    require_signature=require_signature,
                    now_iso=now_iso,
                    revoked_keys=revoked_keys,
                )
            reasons.extend(r for r in inner.reasons if r not in reasons)

            # --- tier 3: evidence cross-binding ------------------------------
            # evidence.json cannot carry its own digest, so EVERY receipt-derived
            # claim it makes is re-derived here from the hash-protected receipt
            # and compared strictly. A forged governed_action / actor / policy
            # section in evidence.json must fail the pack even though the other
            # four artifacts are untouched.
            expected_sections = _receipt_evidence_sections(receipt)
            if evidence.get("receipt") != expected_sections["receipt"]:
                reasons.append(PackRejectionReason.RECEIPT_BINDING_MISMATCH)
            for section in ("governed_action", "actor", "policy"):
                if (
                    evidence.get(section) != expected_sections[section]
                    and PackRejectionReason.EVIDENCE_BINDING_MISMATCH not in reasons
                ):
                    reasons.append(PackRejectionReason.EVIDENCE_BINDING_MISMATCH)
            audit_meta = evidence.get("audit", {})
            audit_meta = audit_meta if isinstance(audit_meta, dict) else {}
            chain_last = chain_doc.get("last_hash")
            actual_last = events[-1].get("event_hash") if events else GENESIS_HASH
            if (
                audit_meta.get("last_hash") != actual_last
                or chain_last != actual_last
                or audit_meta.get("event_count") != len(events)
                or chain_doc.get("event_count") != len(events)
            ):
                reasons.append(PackRejectionReason.AUDIT_BINDING_MISMATCH)
            # Cross-artifact schema pinning, chain half (report half above):
            # the chain must declare the same schema_version evidence.json
            # selected the summary-template revision with.
            if (
                chain_doc.get("schema_version") != schema_version
                and PackRejectionReason.SCHEMA_VERSION_MISMATCH not in reasons
            ):
                reasons.append(PackRejectionReason.SCHEMA_VERSION_MISMATCH)

            # The summary is deterministic given the receipt, the chain, and the
            # replay status, so it is re-rendered here and byte-compared — the
            # auditor/regulator prose cannot be rewritten even by an attacker who
            # recomputes every evidence digest. Rendered with chain valid=True
            # because generation refuses to write a pack from an invalid chain;
            # a chain broken after generation is caught by the inner verifier.
            summary_path = root / SUMMARY_FILE
            if report_doc is not None and summary_path.is_file():
                try:
                    # The footer line ("Generated by ...") records the
                    # generator's identity, which evidence.json carries as an
                    # unauthenticated attestation (no self-digest; not in the
                    # tier-3 re-derived section set). Excise it from the
                    # byte-compare so a generator-identity mismatch does not
                    # block verification of packs produced by a different
                    # vendored copy (e.g. gove_zone.proofpack vs
                    # acgs_proofpack_verifier.proofpack), and so a forged
                    # generator identity cannot be smuggled INTO the
                    # tamper-evident region. The substantive summary content
                    # (receipt, chain, replay) remains byte-bound, AND the
                    # excised suffix must be exactly one known generator footer:
                    # otherwise an attacker who recomputes the unauthenticated
                    # evidence.json digest could append arbitrary Markdown (a
                    # false auditor conclusion) after the separator and still
                    # verify. The body must match EXACTLY the template revision
                    # bound to the pack's declared schema version
                    # (_SUMMARY_REVISION_FOR_SCHEMA): packs issued under an
                    # older schema keep verifying under that schema, while a
                    # newer pack whose summary is swapped for an older
                    # revision's rendering fails — a revision downgrade cannot
                    # silently reinstate superseded auditor wording.
                    shipped = summary_path.read_text(encoding="utf-8")
                    shipped_body, shipped_sep, shipped_footer = shipped.rpartition("\n---\n")
                    expected_body = _render_summary(
                        receipt=receipt,
                        chain={"valid": True},
                        event_count=len(events),
                        replay_report=report_doc,
                        now_iso=str(evidence.get("generated_at")),
                        schema_version=schema_version,
                    ).rsplit("\n---\n", 1)[0]
                    if (
                        not shipped_sep
                        or shipped_body != expected_body
                        or shipped_footer not in _KNOWN_GENERATOR_FOOTERS
                    ):
                        reasons.append(PackRejectionReason.SUMMARY_BINDING_MISMATCH)
                except Exception:  # noqa: BLE001 — an unrenderable summary is a mismatch, never a pass.
                    reasons.append(PackRejectionReason.SUMMARY_BINDING_MISMATCH)
    else:
        # Missing artifacts already recorded in tier 1; the inner tiers cannot run.
        if PackRejectionReason.ARTIFACT_MISSING not in reasons:
            reasons.append(PackRejectionReason.ARTIFACT_MISSING)

    # --- tier 4: replay -------------------------------------------------------
    replay_status = "not_available"
    if report_doc is not None and report_doc.get("status") == "verified":
        # A recorded generate-time report is an ATTESTATION ("recorded"), never
        # treated as re-verification; only an out-of-band re-run upgrades it.
        replay_status = "recorded"

    if (policy_bundle is None) != (side_store is None):
        reasons.append(PackRejectionReason.REPLAY_MATERIAL_MALFORMED)
    elif policy_bundle is not None and side_store is not None:
        replay_status = _reverify_replay(root, Path(policy_bundle), Path(side_store), reasons)

    # --- tier 5 (optional): constitution-hash registry cross-check -----------
    # Fail-closed, and ONLY when the caller supplies a registry; otherwise the
    # optional constitution block is carried but never checked (v1-safe).
    if constitution_registry is not None:
        _crosscheck_constitution(evidence, Path(constitution_registry), reasons)

    valid = (
        integrity_status == "intact"
        and inner is not None
        and inner.valid
        and replay_status != "failed"
        and not reasons
    )
    return PackVerificationResult(
        valid=valid,
        schema_version=schema_version,
        integrity_status=integrity_status,
        receipt_and_chain=inner,
        replay_status=replay_status,
        reasons=reasons,
    )


def _run_inner_verifier(
    tmp: Path,
    *,
    receipt: DecisionReceipt,
    events: list[dict[str, Any]],
    verifier: Any,
    require_signature: bool | None,
    now_iso: str | None,
    revoked_keys: RevocationList | None,
) -> ProofPackVerificationResult:
    """Materialise the gove-zone/proof-pack/v1 shape and reuse its verifier.

    ``event_hash`` covers the canonical JSON of the parsed event dict, not the
    original line bytes, so round-tripping events through ``audit-chain.json``
    preserves verifiability exactly.
    """
    (tmp / "audit.jsonl").write_text(
        "".join(
            json.dumps(e, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n"
            for e in events
        ),
        encoding="utf-8",
    )
    (tmp / "receipt.json").write_text(receipt.to_json() + "\n", encoding="utf-8")
    manifest = {
        "schema_version": INNER_SCHEMA_VERSION,
        "audit_chain": "audit.jsonl",
        "receipts": [
            {
                "name": "decision",
                "file": "receipt.json",
                "declared_verdict": _declared_verdict(receipt),
                "reason_code": None,
            }
        ],
        "replay": None,
        "consumption_ledger": None,
    }
    (tmp / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return verify_proof_pack(
        tmp,
        verifier=verifier,
        require_signature=require_signature,
        now_iso=now_iso,
        revoked_keys=revoked_keys,
    )


def _reverify_replay(root: Path, policy_bundle: Path, side_store: Path, reasons: list[str]) -> str:
    """Re-derive decisions now from out-of-band material (lazy engine import)."""
    try:
        chain_doc = json.loads((root / AUDIT_CHAIN_FILE).read_text(encoding="utf-8"))
        events = chain_doc["events"]
        with tempfile.TemporaryDirectory(prefix="acgs-replay-") as tmp:
            audit_path = Path(tmp) / "audit.jsonl"
            audit_path.write_text(
                "".join(
                    json.dumps(e, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n"
                    for e in events
                ),
                encoding="utf-8",
            )
            result = _run_replay(audit_path, policy_bundle, side_store)
    except Exception:  # noqa: BLE001 — malformed replay material is fail-closed.
        reasons.append(PackRejectionReason.REPLAY_MATERIAL_MALFORMED)
        return "failed"
    if not result.get("valid"):
        reasons.append(PackRejectionReason.REPLAY_MISMATCH)
        return "failed"
    return "reverified"


def _is_hex64(value: Any) -> bool:
    return isinstance(value, str) and len(value) == 64 and all(c in _HEX for c in value)


def _crosscheck_constitution(
    evidence: dict[str, Any], registry_path: Path, reasons: list[str]
) -> None:
    """Fail-closed constitution-hash registry cross-check (G2.5).

    Appends exactly one reason string to ``reasons`` on failure (which flips the
    pack's ``valid`` gate to False). Order of checks: the registry must first be
    readable and well-formed (a non-empty JSON array of 64-hex strings); only
    then is the bundle's stamped ``evidence.constitution.hash`` looked up in it.
    """
    try:
        registry = json.loads(registry_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        reasons.append(CONSTITUTION_REGISTRY_UNREADABLE)
        return

    if not (isinstance(registry, list) and registry and all(_is_hex64(h) for h in registry)):
        reasons.append(CONSTITUTION_REGISTRY_MALFORMED)
        return

    block = evidence.get("constitution")
    bundle_hash = block.get("hash") if isinstance(block, dict) else None
    if not bundle_hash:
        reasons.append(CONSTITUTION_HASH_MISSING)
        return

    if bundle_hash not in registry:
        reasons.append(CONSTITUTION_HASH_NOT_IN_REGISTRY)
