"""Summary body/footer binding contract for the authoritative ACGS-pack verifier.

Two properties, mirroring ``packages/acgs-proofpack-verifier``'s
``test_summary_footer_binding.py`` so the SAME v1 pack never alternates between
valid and invalid depending on which supported verifier checks it:

* **Footer symmetry** — the generator-identity footer (everything after the
  summary's final ``\\n---\\n``) is excised from the tamper-evident byte-compare
  and must be exactly one KNOWN generator footer. A pack generated by the
  standalone ``acgs_proofpack_verifier`` package must verify here, and the
  excision must not become an injection window for arbitrary auditor-facing
  Markdown.
* **Revision tolerance** — the summary body must match ONE accepted template
  revision, so packs issued before an auditor-wording change (still
  ``acgs/proof-pack/v1``) remain verifiable, while any substantive edit to a
  body of either revision still fails closed.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path

import pytest

from gove_zone.proofpack import verify_pack

FIXTURES = Path(__file__).parent / "fixtures"
GOLDEN = FIXTURES / "acgs_proofpack" / "golden"
NOW_ISO = "2026-01-01T00:00:00+00:00"

SUMMARY_BINDING_MISMATCH = "SUMMARY_BINDING_MISMATCH"

STANDALONE_FOOTER = "Generated by `acgs proofpack generate (acgs_proofpack_verifier.proofpack)`.\n"


def _rewrite_summary(pack: Path, new_text: str) -> None:
    """Rewrite verification-summary.md AND recompute its evidence.json digest.

    This models the strongest attacker the summary byte-compare must defeat:
    one who edits the summary and fixes up the unauthenticated evidence.json
    manifest so the tier-1 digest check still passes.
    """
    summary = pack / "verification-summary.md"
    summary.write_text(new_text, encoding="utf-8")
    raw = summary.read_bytes()

    evidence_path = pack / "evidence.json"
    evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    evidence["artifacts"]["verification-summary.md"] = {
        "bytes": len(raw),
        "sha256": hashlib.sha256(raw).hexdigest(),
    }
    evidence_path.write_text(
        json.dumps(evidence, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


@pytest.fixture
def golden_copy(tmp_path: Path) -> Path:
    pack = tmp_path / "pack"
    shutil.copytree(GOLDEN, pack)
    return pack


# --- footer symmetry with the standalone verifier -------------------------------


def test_standalone_generator_footer_is_accepted(golden_copy: Path) -> None:
    """A pack carrying the standalone package's generator identity must verify
    here — the two supported verifiers accept the same footer allowlist."""
    text = (golden_copy / "verification-summary.md").read_text(encoding="utf-8")
    body, sep, _footer = text.rpartition("\n---\n")
    assert sep
    _rewrite_summary(golden_copy, body + sep + STANDALONE_FOOTER)

    result = verify_pack(golden_copy, now_iso=NOW_ISO)
    assert result.valid, [str(r) for r in result.reasons]
    assert result.reasons == []


def test_unknown_generator_footer_is_rejected(golden_copy: Path) -> None:
    text = (golden_copy / "verification-summary.md").read_text(encoding="utf-8")
    body, sep, _footer = text.rpartition("\n---\n")
    assert sep
    _rewrite_summary(golden_copy, body + sep + "Generated by `a totally legit tool`.\n")

    result = verify_pack(golden_copy, now_iso=NOW_ISO)
    assert not result.valid
    assert any(str(r) == SUMMARY_BINDING_MISMATCH for r in result.reasons), [
        str(r) for r in result.reasons
    ]


def test_appended_markdown_after_footer_is_rejected(golden_copy: Path) -> None:
    """A false auditor conclusion appended after the footer must fail the pack,
    even when the evidence.json summary digest is recomputed to match."""
    text = (golden_copy / "verification-summary.md").read_text(encoding="utf-8")
    _rewrite_summary(
        golden_copy,
        text + "\n## Auditor conclusion\n\nIndependently audited: no findings.\n",
    )

    result = verify_pack(golden_copy, now_iso=NOW_ISO)
    assert not result.valid, "arbitrary content after the footer was accepted"
    assert any(str(r) == SUMMARY_BINDING_MISMATCH for r in result.reasons), [
        str(r) for r in result.reasons
    ]


# --- template-revision tolerance -------------------------------------------------

# The revision-1 auditor prose, byte-for-byte as generators emitted it before
# the revision-2 wording change. Historical v1 packs carry these exact bytes;
# they are frozen here as regression evidence and must never be reworded.
_REV2_PROVES_ITEM_3 = """\
3. `evidence.json`'s action / actor / policy sections and this summary's body
   (everything above the trailing generator footer) are re-derived from the
   hash-bound receipt and chain at verify time — a rewritten summary body or
   evidence file fails verification even if every file digest is recomputed
   to match.
"""
_REV1_PROVES_ITEM_3 = """\
3. `evidence.json`'s action / actor / policy sections and this summary are
   re-derived from the hash-bound receipt and chain at verify time — a
   rewritten summary or evidence file fails verification even if every file
   digest is recomputed to match.
"""
_REV2_ATTESTATION_BULLET = """\
- Which tool generated this pack. The trailing "Generated by ..." footer (and
  `generated_with` in `evidence.json`) is an unauthenticated generator
  attestation: it is not derived from the hash-bound receipt or chain, and
  offline verification accepts any known generator identity in its place, so
  it must not be read as authenticated provenance.
"""


def _downgrade_to_revision_1(text: str) -> str:
    """Rewrite a revision-2 summary into the exact revision-1 rendering."""
    assert _REV2_PROVES_ITEM_3 in text
    assert _REV2_ATTESTATION_BULLET in text
    return text.replace(_REV2_PROVES_ITEM_3, _REV1_PROVES_ITEM_3).replace(
        _REV2_ATTESTATION_BULLET, ""
    )


def test_previously_issued_revision_1_summary_still_verifies(golden_copy: Path) -> None:
    """PACK_SCHEMA_VERSION is still acgs/proof-pack/v1, so a pack issued before
    the auditor-wording change (revision-1 summary body) must remain valid —
    a template change must never invalidate historical evidence."""
    text = (golden_copy / "verification-summary.md").read_text(encoding="utf-8")
    _rewrite_summary(golden_copy, _downgrade_to_revision_1(text))

    result = verify_pack(golden_copy, now_iso=NOW_ISO)
    assert result.valid, [str(r) for r in result.reasons]
    assert result.reasons == []


def test_tampered_revision_1_summary_body_is_rejected(golden_copy: Path) -> None:
    """Accepting the older revision must not open a tamper window: an edit to
    a revision-1 body still trips SUMMARY_BINDING_MISMATCH."""
    text = (golden_copy / "verification-summary.md").read_text(encoding="utf-8")
    legacy = _downgrade_to_revision_1(text)
    _rewrite_summary(golden_copy, legacy.replace("PASS", "FAIL", 1))

    result = verify_pack(golden_copy, now_iso=NOW_ISO)
    assert not result.valid
    assert any(str(r) == SUMMARY_BINDING_MISMATCH for r in result.reasons), [
        str(r) for r in result.reasons
    ]


def test_tampered_revision_2_summary_body_is_rejected(golden_copy: Path) -> None:
    text = (golden_copy / "verification-summary.md").read_text(encoding="utf-8")
    _rewrite_summary(golden_copy, text.replace("PASS", "FAIL", 1))

    result = verify_pack(golden_copy, now_iso=NOW_ISO)
    assert not result.valid
    assert any(str(r) == SUMMARY_BINDING_MISMATCH for r in result.reasons), [
        str(r) for r in result.reasons
    ]
