"""Golden + adversarial tests for the ACGS proof pack (``acgs proofpack``).

Three contracts are pinned here:

1. **Byte-golden generation.** The committed ``fixtures/acgs_proofpack/golden``
   bundle regenerates byte-identically from the committed ``valid-replay``
   inputs with the pinned clock — any format drift is a reviewed golden diff,
   never silent.
2. **Fail-closed verification.** Every single-edit tamper of the golden bundle
   is rejected with a stable reason code — including the stronger attacker who
   *recomputes the evidence digests* after tampering the receipt, chain,
   evidence sections, or summary (caught by inner hash binding + re-derivation).
   The documented residual: the generation timestamp and the replay report's
   generate-time status are generator attestations, not offline-provable —
   pinned by test_replay_report_status_never_upgrades_validity.
3. **Engine independence.** ``gove_zone.proofpack`` must not import the policy
   engine at module scope (mirror of the verifier's §5.4 guard); the replay
   tier's engine imports stay lazy.
"""

from __future__ import annotations

import ast
import hashlib
import json
import shutil
from pathlib import Path
from typing import Any

import pytest

cryptography = pytest.importorskip("cryptography")  # the signed-input tests need it

from gove_zone import Ed25519Signer  # noqa: E402
from gove_zone.proofpack import (  # noqa: E402
    ARTIFACT_FILES,
    AUDIT_CHAIN_FILE,
    EVIDENCE_FILE,
    RECEIPT_FILE,
    REPLAY_REPORT_FILE,
    SUMMARY_FILE,
    PackGenerationError,
    PackRejectionReason,
    generate_proof_pack,
    verify_pack,
)
from gove_zone.proofpack_cli import main as acgs_main  # noqa: E402

FIXTURES = Path(__file__).parent / "fixtures"
GOLDEN = FIXTURES / "acgs_proofpack" / "golden"
INPUTS = FIXTURES / "proofpacks" / "valid-replay"
SIGNED_INPUTS = FIXTURES / "proofpacks" / "valid-allow"
_PROOFPACK_SRC = Path(__file__).parents[1] / "src" / "gove_zone" / "proofpack.py"

NOW_ISO = "2026-01-01T00:00:00+00:00"

# Public-key verifier for the signed valid-allow inputs (same fixed fixture seed
# as the receipt/pack corpora; NOT a production key).
_SEED = hashlib.sha256(b"gove-zone fixture corpus v1 :: trusted").digest()
_TRUSTED = Ed25519Signer.from_public_bytes(
    Ed25519Signer.from_private_bytes(_SEED, key_id="fixture-key-1").public_bytes(),
    key_id="fixture-key-1",
)


def _generate_golden(dest: Path) -> None:
    generate_proof_pack(
        dest,
        receipt_path=INPUTS / "receipts" / "r1.json",
        audit_path=INPUTS / "audit.jsonl",
        policy_bundle=INPUTS / "policy_bundle.json",
        side_store=INPUTS / "replay_side_store.jsonl",
        now_iso=NOW_ISO,
    )


def _copy_golden(tmp_path: Path) -> Path:
    dest = tmp_path / "pack"
    shutil.copytree(GOLDEN, dest)
    return dest


def _rehash_evidence(pack: Path) -> None:
    """Recompute the evidence digests after a tamper — the stronger attacker."""
    evidence = json.loads((pack / EVIDENCE_FILE).read_text(encoding="utf-8"))
    for name in ARTIFACT_FILES:
        data = (pack / name).read_bytes()
        evidence["artifacts"][name] = {
            "sha256": hashlib.sha256(data).hexdigest(),
            "bytes": len(data),
        }
    (pack / EVIDENCE_FILE).write_text(
        json.dumps(evidence, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def _edit_json(path: Path, mutate: Any) -> None:
    doc = json.loads(path.read_text(encoding="utf-8"))
    mutate(doc)
    path.write_text(json.dumps(doc, indent=2, sort_keys=True) + "\n", encoding="utf-8")


# --- 1. byte-golden generation -------------------------------------------------


def test_golden_bundle_regenerates_byte_identical(tmp_path: Path) -> None:
    fresh = tmp_path / "regen"
    _generate_golden(fresh)
    fresh_names = sorted(p.name for p in fresh.iterdir())
    golden_names = sorted(p.name for p in GOLDEN.iterdir())
    assert fresh_names == golden_names == sorted([EVIDENCE_FILE, *ARTIFACT_FILES])
    for name in fresh_names:
        assert (fresh / name).read_bytes() == (GOLDEN / name).read_bytes(), (
            f"{name}: regenerated bytes differ from the committed golden — if the "
            "format change is intentional, re-run fixtures/_generate_acgs_proofpack.py "
            "and review the diff"
        )


def test_generated_bundle_forces_lf_at_every_text_write(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Keep proof-pack bytes stable when the host defaults to CRLF."""
    fresh = tmp_path / "regen"
    original_write_text = Path.write_text
    observed: dict[str, str | None] = {}

    def _record_write_text(
        path: Path,
        data: str,
        encoding: str | None = None,
        errors: str | None = None,
        newline: str | None = None,
    ) -> int:
        if path.is_relative_to(fresh):
            observed[path.relative_to(fresh).as_posix()] = newline
        return original_write_text(path, data, encoding=encoding, errors=errors, newline=newline)

    monkeypatch.setattr(Path, "write_text", _record_write_text)
    _generate_golden(fresh)

    expected = sorted([EVIDENCE_FILE, *ARTIFACT_FILES])
    assert sorted(observed) == expected
    assert set(observed.values()) == {"\n"}
    for name in expected:
        payload = (fresh / name).read_bytes()
        assert b"\r" not in payload, f"{name}: unexpected CR/CRLF line ending"
        assert payload.endswith(b"\n"), f"{name}: missing terminal LF"


def test_golden_layout_is_the_documented_contract() -> None:
    # The five files named in the product contract, no more, no less.
    assert sorted(p.name for p in GOLDEN.iterdir()) == sorted(
        [
            "evidence.json",
            "decision-receipt.json",
            "audit-chain.json",
            "replay-report.json",
            "verification-summary.md",
        ]
    )


def test_summary_addresses_all_three_audiences() -> None:
    text = (GOLDEN / SUMMARY_FILE).read_text(encoding="utf-8")
    for heading in ("## For engineers", "## For auditors", "## For regulators"):
        assert heading in text


# --- 2. golden verification ------------------------------------------------------


def test_golden_pack_verifies_valid() -> None:
    result = verify_pack(GOLDEN, now_iso=NOW_ISO)
    assert result.valid, result.reasons
    assert result.integrity_status == "intact"
    assert result.replay_status == "recorded"  # report present, material not supplied
    assert result.receipt_and_chain is not None
    assert result.receipt_and_chain.audit_chain_verified
    assert result.receipt_and_chain.receipts[0].anchored_in_audit_chain
    assert result.reasons == []


def test_golden_pack_replay_reverifies_with_out_of_band_material() -> None:
    result = verify_pack(
        GOLDEN,
        now_iso=NOW_ISO,
        policy_bundle=INPUTS / "policy_bundle.json",
        side_store=INPUTS / "replay_side_store.jsonl",
    )
    assert result.valid, result.reasons
    assert result.replay_status == "reverified"


def test_replay_reverification_rejects_tampered_side_store(tmp_path: Path) -> None:
    side = tmp_path / "side.jsonl"
    entries = [
        json.loads(line)
        for line in (INPUTS / "replay_side_store.jsonl").read_text(encoding="utf-8").splitlines()
    ]
    entries[0]["args"]["path"] = "tampered.txt"
    side.write_text(
        "".join(
            json.dumps(e, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n"
            for e in entries
        ),
        encoding="utf-8",
    )
    result = verify_pack(
        GOLDEN, now_iso=NOW_ISO, policy_bundle=INPUTS / "policy_bundle.json", side_store=side
    )
    assert not result.valid
    assert result.replay_status == "failed"
    assert PackRejectionReason.REPLAY_MISMATCH in result.reasons


# --- 3. tamper matrix -------------------------------------------------------------


def test_tampered_receipt_fails_integrity_and_binding(tmp_path: Path) -> None:
    pack = _copy_golden(tmp_path)
    _edit_json(pack / RECEIPT_FILE, lambda d: d.__setitem__("actor", "attacker"))
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert result.integrity_status == "tampered"
    assert PackRejectionReason.ARTIFACT_DIGEST_MISMATCH in result.reasons


def test_tampered_receipt_with_rehashed_evidence_still_fails(tmp_path: Path) -> None:
    """The stronger attacker: edit the receipt AND recompute every evidence digest.

    Integrity then looks intact — the inner receipt-hash binding must catch it.
    """
    pack = _copy_golden(tmp_path)
    _edit_json(pack / RECEIPT_FILE, lambda d: d.__setitem__("actor", "attacker"))
    _rehash_evidence(pack)
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert result.integrity_status == "intact"  # digests recomputed by the attacker
    assert "RECEIPT_HASH_MISMATCH" in result.reasons


def test_tampered_chain_with_rehashed_evidence_still_fails(tmp_path: Path) -> None:
    pack = _copy_golden(tmp_path)

    def _flip(doc: dict[str, Any]) -> None:
        h = doc["events"][0]["event_hash"]
        doc["events"][0]["event_hash"] = ("0" if h[0] != "0" else "f") + h[1:]

    _edit_json(pack / AUDIT_CHAIN_FILE, _flip)
    _rehash_evidence(pack)
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert "AUDIT_CHAIN_BROKEN" in result.reasons


def test_truncated_chain_with_rehashed_evidence_fails_binding(tmp_path: Path) -> None:
    """Dropping the trailing event breaks the evidence/chain last-hash cross-binding."""
    pack = _copy_golden(tmp_path)
    _edit_json(pack / AUDIT_CHAIN_FILE, lambda d: d["events"].pop())
    _rehash_evidence(pack)
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert PackRejectionReason.AUDIT_BINDING_MISMATCH in result.reasons


def test_tampered_summary_fails_integrity(tmp_path: Path) -> None:
    pack = _copy_golden(tmp_path)
    summary = pack / SUMMARY_FILE
    summary.write_text(
        summary.read_text(encoding="utf-8").replace("**ALLOW**", "**DENY**"),
        encoding="utf-8",
    )
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert result.integrity_status == "tampered"


def test_tampered_summary_with_rehashed_evidence_still_fails(tmp_path: Path) -> None:
    """Code-review HIGH regression: the auditor/regulator prose must not be
    rewritable even by the attacker who recomputes every evidence digest. The
    summary is re-derived from the hash-bound receipt at verify time.
    """
    pack = _copy_golden(tmp_path)
    summary = pack / SUMMARY_FILE
    summary.write_text(
        summary.read_text(encoding="utf-8").replace(
            "`runtime.file.write`", "`runtime.harmless.noop`"
        ),
        encoding="utf-8",
    )
    _rehash_evidence(pack)
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert result.integrity_status == "intact"  # digests recomputed by the attacker
    assert PackRejectionReason.SUMMARY_BINDING_MISMATCH in result.reasons


def test_forged_replay_status_with_rehashed_evidence_fails_summary_binding(
    tmp_path: Path,
) -> None:
    # Downgrading/upgrading the replay status desynchronises the summary's
    # replay line from the report; the re-render catches it.
    pack = _copy_golden(tmp_path)
    _edit_json(pack / REPLAY_REPORT_FILE, lambda d: d.__setitem__("status", "not_available"))
    _rehash_evidence(pack)
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert PackRejectionReason.SUMMARY_BINDING_MISMATCH in result.reasons


def test_replay_report_status_never_upgrades_validity(tmp_path: Path) -> None:
    """Pin the attestation boundary: a recorded 'verified' replay report yields
    replay_status='recorded' (a generator claim), never 'reverified' — so a
    fully-consistent forgery of the report can at most claim, not prove.
    """
    result = verify_pack(GOLDEN, now_iso=NOW_ISO)
    assert result.replay_status == "recorded"
    assert result.valid  # and validity never depends on the recorded status


def test_malformed_replay_report_fails_closed(tmp_path: Path) -> None:
    pack = _copy_golden(tmp_path)
    _edit_json(pack / REPLAY_REPORT_FILE, lambda d: d.__setitem__("status", "totally-fine"))
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert PackRejectionReason.REPLAY_REPORT_MALFORMED in result.reasons


def test_evidence_not_json_fails_closed(tmp_path: Path) -> None:
    pack = _copy_golden(tmp_path)
    (pack / EVIDENCE_FILE).write_text("not json {", encoding="utf-8")
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert PackRejectionReason.EVIDENCE_MALFORMED in result.reasons


def test_missing_schema_version_fails_closed(tmp_path: Path) -> None:
    pack = _copy_golden(tmp_path)
    _edit_json(pack / EVIDENCE_FILE, lambda d: d.pop("schema_version"))
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert PackRejectionReason.SCHEMA_VERSION_MISSING in result.reasons


def test_unexpected_exception_maps_to_verifier_error() -> None:
    # Path(12345) raises TypeError before any tier runs; the top-level guard
    # must fold it into a fail-closed verdict, never an escaping exception.
    result = verify_pack(12345)  # type: ignore[arg-type]
    assert not result.valid
    assert PackRejectionReason.VERIFIER_ERROR in result.reasons


def test_missing_artifact_is_incomplete(tmp_path: Path) -> None:
    pack = _copy_golden(tmp_path)
    (pack / REPLAY_REPORT_FILE).unlink()
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert result.integrity_status == "incomplete"
    assert PackRejectionReason.ARTIFACT_MISSING in result.reasons


def test_missing_evidence_fails_closed(tmp_path: Path) -> None:
    pack = _copy_golden(tmp_path)
    (pack / EVIDENCE_FILE).unlink()
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert PackRejectionReason.EVIDENCE_MISSING in result.reasons


def test_unsupported_schema_version_fails_closed(tmp_path: Path) -> None:
    pack = _copy_golden(tmp_path)
    _edit_json(
        pack / EVIDENCE_FILE,
        lambda d: d.__setitem__("schema_version", "acgs/proof-pack/v0"),
    )
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert PackRejectionReason.SCHEMA_VERSION_UNSUPPORTED in result.reasons


@pytest.mark.parametrize(
    ("section", "key", "forged"),
    [
        ("governed_action", "proposed_action", "runtime.SUDO.rm_rf_root"),
        ("governed_action", "decision", "deny"),
        ("actor", "id", "attacker-controlled-actor"),
        ("policy", "bundle_id", "forged-policy/v99"),
        ("policy", "hash", "0" * 64),
    ],
)
def test_forged_evidence_descriptive_sections_are_caught(
    tmp_path: Path, section: str, key: str, forged: str
) -> None:
    """Governance-review BLOCKER regression: evidence.json carries no digest of
    itself, so its receipt-derived sections MUST be re-derived from the
    hash-protected receipt at verify time. A forged action/actor/policy in
    evidence.json (with all other artifacts untouched) must fail the pack.
    """
    pack = _copy_golden(tmp_path)
    _edit_json(pack / EVIDENCE_FILE, lambda d: d[section].__setitem__(key, forged))
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert result.integrity_status == "intact"  # the four artifacts are untouched
    assert PackRejectionReason.EVIDENCE_BINDING_MISMATCH in result.reasons


def test_forged_evidence_event_count_is_caught(tmp_path: Path) -> None:
    pack = _copy_golden(tmp_path)
    _edit_json(pack / EVIDENCE_FILE, lambda d: d["audit"].__setitem__("event_count", 99))
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert PackRejectionReason.AUDIT_BINDING_MISMATCH in result.reasons


def test_multiple_missing_artifacts_report_reason_once(tmp_path: Path) -> None:
    pack = _copy_golden(tmp_path)
    (pack / REPLAY_REPORT_FILE).unlink()
    (pack / SUMMARY_FILE).unlink()
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert result.reasons.count(PackRejectionReason.ARTIFACT_MISSING) == 1


def test_evidence_receipt_hash_mismatch_is_caught(tmp_path: Path) -> None:
    pack = _copy_golden(tmp_path)
    _edit_json(
        pack / EVIDENCE_FILE,
        lambda d: d["receipt"].__setitem__("receipt_hash", "0" * 64),
    )
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert PackRejectionReason.RECEIPT_BINDING_MISMATCH in result.reasons


def test_nonexistent_pack_fails_closed(tmp_path: Path) -> None:
    result = verify_pack(tmp_path / "no-such-pack")
    assert not result.valid
    assert PackRejectionReason.PACK_NOT_FOUND in result.reasons


# --- 4. signed inputs --------------------------------------------------------------


def _generate_signed(tmp_path: Path) -> Path:
    dest = tmp_path / "signed-pack"
    generate_proof_pack(
        dest,
        receipt_path=SIGNED_INPUTS / "receipts" / "allow.json",
        audit_path=SIGNED_INPUTS / "audit.jsonl",
        now_iso=NOW_ISO,
    )
    return dest


def test_signed_pack_verifies_with_trusted_key(tmp_path: Path) -> None:
    pack = _generate_signed(tmp_path)
    result = verify_pack(pack, verifier={"fixture-key-1": _TRUSTED}, now_iso=NOW_ISO)
    assert result.valid, result.reasons
    assert result.receipt_and_chain is not None
    assert result.receipt_and_chain.receipts[0].signature_verified is True


def test_signed_pack_without_key_fails_closed(tmp_path: Path) -> None:
    # A signed accept receipt with no trust anchor must reject, never degrade.
    pack = _generate_signed(tmp_path)
    result = verify_pack(pack, now_iso=NOW_ISO)
    assert not result.valid
    assert "RECEIPT_UNEXPECTED_REJECT" in result.reasons


# --- 5. generation refusals ---------------------------------------------------------


def test_generate_refuses_unanchored_receipt(tmp_path: Path) -> None:
    # Receipt from one chain, audit events from another: not anchored.
    with pytest.raises(PackGenerationError, match="not anchored"):
        generate_proof_pack(
            tmp_path / "pack",
            receipt_path=SIGNED_INPUTS / "receipts" / "allow.json",
            audit_path=INPUTS / "audit.jsonl",
        )


def test_generate_refuses_tampered_receipt_input(tmp_path: Path) -> None:
    bad = tmp_path / "receipt.json"
    doc = json.loads((INPUTS / "receipts" / "r1.json").read_text(encoding="utf-8"))
    doc["actor"] = "attacker"
    bad.write_text(json.dumps(doc), encoding="utf-8")
    with pytest.raises(PackGenerationError, match="binding is broken"):
        generate_proof_pack(tmp_path / "pack", receipt_path=bad, audit_path=INPUTS / "audit.jsonl")


def test_generate_refuses_broken_chain(tmp_path: Path) -> None:
    broken = FIXTURES / "proofpacks" / "chain-break"
    with pytest.raises(PackGenerationError, match="chain"):
        generate_proof_pack(
            tmp_path / "pack",
            receipt_path=broken / "receipts" / "allow.json",
            audit_path=broken / "audit.jsonl",
        )


def test_generate_refuses_failed_replay(tmp_path: Path) -> None:
    mismatch = FIXTURES / "proofpacks" / "replay-mismatch"
    with pytest.raises(PackGenerationError, match="replay FAILED"):
        generate_proof_pack(
            tmp_path / "pack",
            receipt_path=mismatch / "receipts" / "r1.json",
            audit_path=mismatch / "audit.jsonl",
            policy_bundle=mismatch / "policy_bundle.json",
            side_store=mismatch / "replay_side_store.jsonl",
        )


def test_generate_refuses_half_supplied_replay_material(tmp_path: Path) -> None:
    with pytest.raises(PackGenerationError, match="BOTH"):
        generate_proof_pack(
            tmp_path / "pack",
            receipt_path=INPUTS / "receipts" / "r1.json",
            audit_path=INPUTS / "audit.jsonl",
            policy_bundle=INPUTS / "policy_bundle.json",
        )


def test_generate_rejects_invalid_now_iso(tmp_path: Path) -> None:
    with pytest.raises(PackGenerationError, match="ISO-8601"):
        generate_proof_pack(
            tmp_path / "pack",
            receipt_path=INPUTS / "receipts" / "r1.json",
            audit_path=INPUTS / "audit.jsonl",
            now_iso="yesterday-ish",
        )


def test_generate_refuses_overwrite_without_force(tmp_path: Path) -> None:
    dest = tmp_path / "pack"
    _generate_golden(dest)
    with pytest.raises(PackGenerationError, match="refusing to overwrite"):
        generate_proof_pack(
            dest,
            receipt_path=INPUTS / "receipts" / "r1.json",
            audit_path=INPUTS / "audit.jsonl",
        )


# --- 6. CLI ---------------------------------------------------------------------------


def test_cli_generate_then_verify_roundtrip(tmp_path: Path, capsys: Any) -> None:
    out = tmp_path / "pack"
    rc = acgs_main(
        [
            "proofpack",
            "generate",
            "--receipt",
            str(INPUTS / "receipts" / "r1.json"),
            "--audit",
            str(INPUTS / "audit.jsonl"),
            "--out",
            str(out),
            "--now-iso",
            NOW_ISO,
        ]
    )
    assert rc == 0
    summary = json.loads(capsys.readouterr().out)
    assert summary["status"] == "pass"
    assert sorted(summary["files"]) == sorted([EVIDENCE_FILE, *ARTIFACT_FILES])

    rc = acgs_main(["proofpack", "verify", str(out), "--now-iso", NOW_ISO])
    assert rc == 0
    report = json.loads(capsys.readouterr().out)
    assert report["valid"] is True
    assert report["integrity_status"] == "intact"


def test_cli_verify_exits_1_on_tampered_pack(tmp_path: Path, capsys: Any) -> None:
    pack = _copy_golden(tmp_path)
    _edit_json(pack / RECEIPT_FILE, lambda d: d.__setitem__("actor", "attacker"))
    rc = acgs_main(["proofpack", "verify", str(pack), "--now-iso", NOW_ISO])
    assert rc == 1
    report = json.loads(capsys.readouterr().out)
    assert report["valid"] is False


def test_cli_generate_exits_1_on_refusal(tmp_path: Path, capsys: Any) -> None:
    broken = FIXTURES / "proofpacks" / "chain-break"
    rc = acgs_main(
        [
            "proofpack",
            "generate",
            "--receipt",
            str(broken / "receipts" / "allow.json"),
            "--audit",
            str(broken / "audit.jsonl"),
            "--out",
            str(tmp_path / "pack"),
        ]
    )
    assert rc == 1
    assert "refusing" in capsys.readouterr().err


def test_cli_verify_signed_pack_with_real_key_file(tmp_path: Path, capsys: Any) -> None:
    pack = _generate_signed(tmp_path)
    key_file = tmp_path / "trusted.pub"
    key_file.write_bytes(_TRUSTED.public_bytes())
    rc = acgs_main(
        [
            "proofpack",
            "verify",
            str(pack),
            "--verifier-key",
            str(key_file),
            "--key-id",
            "fixture-key-1",
            "--require-signature",
            "--now-iso",
            NOW_ISO,
        ]
    )
    assert rc == 0
    assert json.loads(capsys.readouterr().out)["valid"] is True


def test_cli_verify_revoked_key_fails(tmp_path: Path, capsys: Any) -> None:
    pack = _generate_signed(tmp_path)
    key_file = tmp_path / "trusted.pub"
    key_file.write_bytes(_TRUSTED.public_bytes())
    revoked = tmp_path / "revoked.json"
    revoked.write_text(json.dumps(["fixture-key-1"]), encoding="utf-8")
    rc = acgs_main(
        [
            "proofpack",
            "verify",
            str(pack),
            "--verifier-key",
            str(key_file),
            "--key-id",
            "fixture-key-1",
            "--revoked-keys",
            str(revoked),
            "--now-iso",
            NOW_ISO,
        ]
    )
    assert rc == 1
    assert json.loads(capsys.readouterr().out)["valid"] is False


def test_cli_require_signature_rejects_unsigned_pack(capsys: Any) -> None:
    # The golden pack is unsigned (dev posture); an auditor demanding signatures
    # must get a fail-closed verdict from the CLI.
    rc = acgs_main(
        ["proofpack", "verify", str(GOLDEN), "--require-signature", "--now-iso", NOW_ISO]
    )
    assert rc == 1
    report = json.loads(capsys.readouterr().out)
    assert report["valid"] is False
    assert "UNSIGNED_REJECTED" in report["reasons"]


def test_cli_verify_exits_2_on_half_supplied_replay_material(capsys: Any) -> None:
    # Usage error, not a pack verdict: a valid pack must not look tampered
    # because the caller forgot one of the two replay flags.
    rc = acgs_main(
        [
            "proofpack",
            "verify",
            str(GOLDEN),
            "--policy-bundle",
            str(INPUTS / "policy_bundle.json"),
        ]
    )
    assert rc == 2
    assert "must be supplied together" in capsys.readouterr().err


def test_cli_verify_exits_2_on_bad_trust_anchor(tmp_path: Path, capsys: Any) -> None:
    rc = acgs_main(
        [
            "proofpack",
            "verify",
            str(GOLDEN),
            "--verifier-key",
            str(tmp_path / "no-such-key"),
        ]
    )
    assert rc == 2
    assert "cannot load --verifier-key" in capsys.readouterr().err


# --- 7. engine independence (mirror of the verifier's §5.4 AST guard) -----------------


def test_proofpack_module_is_engine_independent() -> None:
    tree = ast.parse(_PROOFPACK_SRC.read_text(encoding="utf-8"))
    engine = {
        "gove_zone.kernel",
        "gove_zone.executor",
        "gove_zone.policy",
        "gove_zone.replay",
        "gove_zone.replay_store",
    }

    def _imported_modules(nodes: Any) -> set[str]:
        mods: set[str] = set()
        for node in nodes:
            if isinstance(node, ast.Import):
                mods.update(alias.name for alias in node.names)
            elif isinstance(node, ast.ImportFrom) and node.module:
                mods.add(node.module)
        return mods

    module_scope = _imported_modules(
        n for n in tree.body if isinstance(n, (ast.Import, ast.ImportFrom))
    )
    function_scope: set[str] = set()
    for fn in ast.walk(tree):
        if isinstance(fn, (ast.FunctionDef, ast.AsyncFunctionDef)):
            function_scope |= _imported_modules(
                x for x in ast.walk(fn) if isinstance(x, (ast.Import, ast.ImportFrom))
            )

    assert not (module_scope & engine), (
        f"proofpack.py imports the engine at module scope: {sorted(module_scope & engine)}"
    )
    assert {"gove_zone.policy", "gove_zone.replay", "gove_zone.replay_store"} <= function_scope, (
        f"lazy replay-tier imports missing from function bodies: {sorted(function_scope)}"
    )
