"""Summary body/footer binding contract for the authoritative ACGS-pack verifier.

Two properties, mirroring ``packages/acgs-proofpack-verifier``'s
``test_summary_footer_binding.py`` so the SAME v1 pack never alternates between
valid and invalid depending on which supported verifier checks it:

* **Footer symmetry** — the generator-identity footer (everything after the
  summary's final ``\\n---\\n``) is excised from the tamper-evident byte-compare
  and must be exactly one KNOWN generator footer. A pack generated by the
  standalone ``acgs_proofpack_verifier`` package must verify here, and the
  excision must not become an injection window for arbitrary auditor-facing
  Markdown.
* **Schema-bound revisions** — the summary body must match EXACTLY the
  template revision bound to the pack's declared schema version. Genuinely
  historical ``acgs/proof-pack/v1`` packs (committed golden-v1 fixture,
  byte-for-byte as the pre-revision generator emitted them) remain verifiable,
  while swapping a current ``acgs/proof-pack/v1.1`` pack's summary for the
  revision-1 rendering — the revision-downgrade attack — fails closed, as does
  any substantive edit to a body of either revision.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path

import pytest

from gove_zone.proofpack import verify_pack

FIXTURES = Path(__file__).parent / "fixtures"
GOLDEN = FIXTURES / "acgs_proofpack" / "golden"
# A genuinely historical acgs/proof-pack/v1 pack, byte-for-byte as the
# pre-revision-2 generator emitted it (resurrected from the parent commit).
GOLDEN_V1 = FIXTURES / "acgs_proofpack" / "golden-v1"
NOW_ISO = "2026-01-01T00:00:00+00:00"

SUMMARY_BINDING_MISMATCH = "SUMMARY_BINDING_MISMATCH"
SCHEMA_VERSION_MISMATCH = "SCHEMA_VERSION_MISMATCH"

STANDALONE_FOOTER = "Generated by `acgs proofpack generate (acgs_proofpack_verifier.proofpack)`.\n"


def _rewrite_summary(pack: Path, new_text: str) -> None:
    """Rewrite verification-summary.md AND recompute its evidence.json digest.

    This models the strongest attacker the summary byte-compare must defeat:
    one who edits the summary and fixes up the unauthenticated evidence.json
    manifest so the tier-1 digest check still passes.
    """
    summary = pack / "verification-summary.md"
    summary.write_text(new_text, encoding="utf-8")
    raw = summary.read_bytes()

    evidence_path = pack / "evidence.json"
    evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    evidence["artifacts"]["verification-summary.md"] = {
        "bytes": len(raw),
        "sha256": hashlib.sha256(raw).hexdigest(),
    }
    evidence_path.write_text(
        json.dumps(evidence, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


@pytest.fixture
def golden_copy(tmp_path: Path) -> Path:
    pack = tmp_path / "pack"
    shutil.copytree(GOLDEN, pack)
    return pack


@pytest.fixture
def golden_v1_copy(tmp_path: Path) -> Path:
    pack = tmp_path / "pack-v1"
    shutil.copytree(GOLDEN_V1, pack)
    return pack


# --- footer symmetry with the standalone verifier -------------------------------


def test_standalone_generator_footer_is_accepted(golden_copy: Path) -> None:
    """A pack carrying the standalone package's generator identity must verify
    here — the two supported verifiers accept the same footer allowlist."""
    text = (golden_copy / "verification-summary.md").read_text(encoding="utf-8")
    body, sep, _footer = text.rpartition("\n---\n")
    assert sep
    _rewrite_summary(golden_copy, body + sep + STANDALONE_FOOTER)

    result = verify_pack(golden_copy, now_iso=NOW_ISO)
    assert result.valid, [str(r) for r in result.reasons]
    assert result.reasons == []


def test_unknown_generator_footer_is_rejected(golden_copy: Path) -> None:
    text = (golden_copy / "verification-summary.md").read_text(encoding="utf-8")
    body, sep, _footer = text.rpartition("\n---\n")
    assert sep
    _rewrite_summary(golden_copy, body + sep + "Generated by `a totally legit tool`.\n")

    result = verify_pack(golden_copy, now_iso=NOW_ISO)
    assert not result.valid
    assert any(str(r) == SUMMARY_BINDING_MISMATCH for r in result.reasons), [
        str(r) for r in result.reasons
    ]


def test_appended_markdown_after_footer_is_rejected(golden_copy: Path) -> None:
    """A false auditor conclusion appended after the footer must fail the pack,
    even when the evidence.json summary digest is recomputed to match."""
    text = (golden_copy / "verification-summary.md").read_text(encoding="utf-8")
    _rewrite_summary(
        golden_copy,
        text + "\n## Auditor conclusion\n\nIndependently audited: no findings.\n",
    )

    result = verify_pack(golden_copy, now_iso=NOW_ISO)
    assert not result.valid, "arbitrary content after the footer was accepted"
    assert any(str(r) == SUMMARY_BINDING_MISMATCH for r in result.reasons), [
        str(r) for r in result.reasons
    ]


# --- schema-bound template revisions ----------------------------------------------

# The revision-1 auditor prose, byte-for-byte as generators emitted it before
# the revision-2 wording change. Historical v1 packs carry these exact bytes;
# they are frozen here as regression evidence and must never be reworded.
_REV2_PROVES_ITEM_3 = """\
3. `evidence.json`'s action / actor / policy sections and this summary's body
   (everything above the trailing generator footer) are re-rendered and
   byte-compared at verify time. Prose derived from the hash-bound receipt
   and chain cannot be rewritten without failing verification, even if every
   file digest is recomputed to match. The body's generation timestamp and
   replay-status wording are rendered from the pack's own recorded
   attestations (`evidence.json`, `replay-report.json`), so they are exactly
   as trustworthy as those attestations (see below).
"""
_REV1_PROVES_ITEM_3 = """\
3. `evidence.json`'s action / actor / policy sections and this summary are
   re-derived from the hash-bound receipt and chain at verify time — a
   rewritten summary or evidence file fails verification even if every file
   digest is recomputed to match.
"""
_REV2_ATTESTATION_BULLET = """\
- Which tool generated this pack. The trailing "Generated by ..." footer (and
  `generated_with` in `evidence.json`) is an unauthenticated generator
  attestation: it is not derived from the hash-bound receipt or chain, and
  offline verification accepts any known generator identity in its place, so
  it must not be read as authenticated provenance.
"""


def _downgrade_to_revision_1(text: str) -> str:
    """Rewrite a revision-2 summary into the exact revision-1 rendering,
    including the older schema line — the strongest summary-only downgrade an
    editor can produce without also rewriting the pack's declared
    schema_version in evidence.json."""
    assert _REV2_PROVES_ITEM_3 in text
    assert _REV2_ATTESTATION_BULLET in text
    return (
        text.replace(_REV2_PROVES_ITEM_3, _REV1_PROVES_ITEM_3)
        .replace(_REV2_ATTESTATION_BULLET, "")
        .replace("Schema: `acgs/proof-pack/v1.1`", "Schema: `acgs/proof-pack/v1`")
    )


def test_historical_v1_pack_still_verifies() -> None:
    """A genuinely historical acgs/proof-pack/v1 pack (committed byte-for-byte
    as the pre-revision-2 generator emitted it) must remain valid — a template
    change must never invalidate previously issued evidence."""
    result = verify_pack(GOLDEN_V1, now_iso=NOW_ISO)
    assert result.valid, [str(r) for r in result.reasons]
    assert result.reasons == []


def test_revision_downgrade_of_current_pack_is_rejected(golden_copy: Path) -> None:
    """The downgrade attack: replacing a current v1.1 pack's summary with the
    exact revision-1 rendering (and recomputing the unauthenticated
    evidence.json digest) must FAIL — the revision is bound to the pack's
    declared schema version, so superseded auditor wording cannot be silently
    reinstated on a current pack."""
    text = (golden_copy / "verification-summary.md").read_text(encoding="utf-8")
    _rewrite_summary(golden_copy, _downgrade_to_revision_1(text))

    result = verify_pack(golden_copy, now_iso=NOW_ISO)
    assert not result.valid, "revision-downgraded summary was accepted on a v1.1 pack"
    assert any(str(r) == SUMMARY_BINDING_MISMATCH for r in result.reasons), [
        str(r) for r in result.reasons
    ]


def test_mixed_version_downgrade_is_rejected(golden_copy: Path) -> None:
    """The cheaper downgrade: rewrite ONLY evidence.json's declared
    schema_version to v1 and substitute the exact revision-1 summary rendering
    (recomputing the unauthenticated digest) while audit-chain.json and
    replay-report.json still declare v1.1. The schema-bound summary compare
    alone would accept this mixed-version pack, so cross-artifact schema
    pinning must fail it: every artifact that declares a schema_version must
    declare the one evidence.json selected the template revision with."""
    evidence_path = golden_copy / "evidence.json"
    evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    assert evidence["schema_version"] == "acgs/proof-pack/v1.1"
    evidence["schema_version"] = "acgs/proof-pack/v1"
    evidence_path.write_text(
        json.dumps(evidence, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    text = (golden_copy / "verification-summary.md").read_text(encoding="utf-8")
    _rewrite_summary(golden_copy, _downgrade_to_revision_1(text))

    result = verify_pack(golden_copy, now_iso=NOW_ISO)
    assert not result.valid, "mixed-version downgraded pack was accepted"
    assert any(str(r) == SCHEMA_VERSION_MISMATCH for r in result.reasons), [
        str(r) for r in result.reasons
    ]


def test_revision_2_body_on_v1_pack_is_rejected(golden_v1_copy: Path) -> None:
    """The mirror-image mix: a v1 pack whose summary carries the revision-2
    body must fail too — no cross-revision acceptance in either direction."""
    text = (golden_v1_copy / "verification-summary.md").read_text(encoding="utf-8")
    assert _REV1_PROVES_ITEM_3.rstrip("\n") in text
    upgraded = text.replace(_REV1_PROVES_ITEM_3.rstrip("\n"), _REV2_PROVES_ITEM_3.rstrip("\n"))
    _rewrite_summary(golden_v1_copy, upgraded)

    result = verify_pack(golden_v1_copy, now_iso=NOW_ISO)
    assert not result.valid
    assert any(str(r) == SUMMARY_BINDING_MISMATCH for r in result.reasons), [
        str(r) for r in result.reasons
    ]


def test_tampered_revision_1_summary_body_is_rejected(golden_v1_copy: Path) -> None:
    """Accepting historical v1 packs must not open a tamper window: an edit to
    a genuine revision-1 body still trips SUMMARY_BINDING_MISMATCH."""
    text = (golden_v1_copy / "verification-summary.md").read_text(encoding="utf-8")
    _rewrite_summary(golden_v1_copy, text.replace("PASS", "FAIL", 1))

    result = verify_pack(golden_v1_copy, now_iso=NOW_ISO)
    assert not result.valid
    assert any(str(r) == SUMMARY_BINDING_MISMATCH for r in result.reasons), [
        str(r) for r in result.reasons
    ]


def test_tampered_revision_2_summary_body_is_rejected(golden_copy: Path) -> None:
    text = (golden_copy / "verification-summary.md").read_text(encoding="utf-8")
    _rewrite_summary(golden_copy, text.replace("PASS", "FAIL", 1))

    result = verify_pack(golden_copy, now_iso=NOW_ISO)
    assert not result.valid
    assert any(str(r) == SUMMARY_BINDING_MISMATCH for r in result.reasons), [
        str(r) for r in result.reasons
    ]
