"""Tests for scripts/verify_constitutional_hashes.py.

Covers the four classes of behavior:
  - Marker recognition (regex tolerance across observed formats)
  - Inventory construction (walk, skip rules, encoding edge cases)
  - Lock file I/O (round-trip, schema validation)
  - Diff + CLI exit codes

Sampled real markers from packages/acgs-lite/:
    Constitutional Hash: 608508a9bd224290
    Constitutional Hash: `608508a9bd224290`
    *Constitutional Hash: `608508a9bd224290` — embedded in every validation path.*
    "*Generated by acgs-lite · Constitutional Hash: `608508a9bd224290`*",
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest
import verify_constitutional_hashes as verifier

ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "scripts" / "verify_constitutional_hashes.py"
SAMPLE_HASH = "608508a9bd224290"


# ---------------------------------------------------------------------------
# Marker regex — must match every format observed in packages/acgs-lite
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("line", [
    "# Constitutional Hash: 608508a9bd224290",
    "Constitutional Hash: 608508a9bd224290",
    "# Constitutional Hash: `608508a9bd224290`",
    "Constitutional Hash: `608508a9bd224290`",
    "*Constitutional Hash: `608508a9bd224290`*",
    "> Constitutional Hash: `608508a9bd224290`",
    "*Constitutional Hash: `608508a9bd224290` — embedded in every validation path.*",
    "    Constitutional Hash:   608508a9bd224290   # trailing comment",
])
def test_regex_matches_observed_marker_formats(line):
    m = verifier.MARKER_RE.search(line)
    assert m is not None, f"Regex failed to match real marker form: {line!r}"
    assert m.group(1) == SAMPLE_HASH


def test_regex_captures_hash_inside_string_literal():
    """Marker embedded in a Python string constant (seen in __init__.py)."""
    line = '"*Generated by acgs-lite · Constitutional Hash: `608508a9bd224290`*",'
    m = verifier.MARKER_RE.search(line)
    assert m is not None
    assert m.group(1) == SAMPLE_HASH


def test_regex_rejects_non_hex_value():
    line = "Constitutional Hash: not-a-hash-value"
    m = verifier.MARKER_RE.search(line)
    assert m is None


def test_regex_is_case_insensitive_on_hex():
    line = "Constitutional Hash: ABCDEF0123456789"
    m = verifier.MARKER_RE.search(line)
    assert m is not None
    assert m.group(1) == "ABCDEF0123456789"


# ---------------------------------------------------------------------------
# Inventory construction — _scan_file
# ---------------------------------------------------------------------------

def test_scan_file_returns_none_when_no_marker(tmp_path, monkeypatch):
    monkeypatch.setattr(verifier, "REPO_ROOT", tmp_path)
    (tmp_path / "plain.py").write_text("def f():\n    return 1\n")
    assert verifier._scan_file(Path("plain.py")) is None


def test_scan_file_extracts_bare_marker(tmp_path, monkeypatch):
    monkeypatch.setattr(verifier, "REPO_ROOT", tmp_path)
    (tmp_path / "policy.py").write_text(f"# Constitutional Hash: {SAMPLE_HASH}\n")
    assert verifier._scan_file(Path("policy.py")) == SAMPLE_HASH


def test_scan_file_extracts_backticked_marker(tmp_path, monkeypatch):
    """This test FAILED before regex fix; locks in tolerance for backticks."""
    monkeypatch.setattr(verifier, "REPO_ROOT", tmp_path)
    (tmp_path / "doc.md").write_text(f"> Constitutional Hash: `{SAMPLE_HASH}`\n")
    assert verifier._scan_file(Path("doc.md")) == SAMPLE_HASH


def test_scan_file_returns_first_marker_when_many(tmp_path, monkeypatch):
    monkeypatch.setattr(verifier, "REPO_ROOT", tmp_path)
    content = f"# Constitutional Hash: {SAMPLE_HASH}\n# Constitutional Hash: aaaaaaaaaaaaaaaa\n"
    (tmp_path / "double.py").write_text(content)
    assert verifier._scan_file(Path("double.py")) == SAMPLE_HASH


def test_scan_file_handles_non_utf8_bytes(tmp_path, monkeypatch):
    monkeypatch.setattr(verifier, "REPO_ROOT", tmp_path)
    p = tmp_path / "binary.py"
    p.write_bytes(b"\xff\xfe binary garbage \xc3\x28 Constitutional Hash: " + SAMPLE_HASH.encode())
    # errors="ignore" + marker still parseable from the surviving bytes.
    result = verifier._scan_file(Path("binary.py"))
    assert result == SAMPLE_HASH


def test_scan_file_only_reads_first_4kb(tmp_path, monkeypatch):
    """Markers past 4KB are intentionally missed — documented limitation."""
    monkeypatch.setattr(verifier, "REPO_ROOT", tmp_path)
    p = tmp_path / "buried.py"
    padding = "# noop\n" * 1000  # >> 4KB
    p.write_text(padding + f"# Constitutional Hash: {SAMPLE_HASH}\n")
    assert verifier._scan_file(Path("buried.py")) is None


def test_scan_file_missing_file_returns_none(tmp_path, monkeypatch):
    monkeypatch.setattr(verifier, "REPO_ROOT", tmp_path)
    assert verifier._scan_file(Path("ghost.py")) is None


# ---------------------------------------------------------------------------
# build_inventory — git ls-files integration
# ---------------------------------------------------------------------------

def _init_git(path: Path) -> None:
    subprocess.run(["git", "init", "-q"], cwd=path, check=True)
    subprocess.run(["git", "config", "user.email", "t@t"], cwd=path, check=True)
    subprocess.run(["git", "config", "user.name", "t"], cwd=path, check=True)


def test_build_inventory_in_isolated_tree(tmp_path, monkeypatch):
    monkeypatch.setattr(verifier, "REPO_ROOT", tmp_path)
    _init_git(tmp_path)
    (tmp_path / "a.py").write_text(f"# Constitutional Hash: {SAMPLE_HASH}\n")
    (tmp_path / "b.md").write_text(f"Constitutional Hash: `{SAMPLE_HASH}`\n")
    (tmp_path / "c.py").write_text("# no marker here\n")
    subprocess.run(["git", "add", "."], cwd=tmp_path, check=True)
    subprocess.run(["git", "commit", "-qm", "init"], cwd=tmp_path, check=True)

    inv = verifier.build_inventory()
    assert inv == {"a.py": SAMPLE_HASH, "b.md": SAMPLE_HASH}


def test_build_inventory_skips_non_scanned_extensions(tmp_path, monkeypatch):
    monkeypatch.setattr(verifier, "REPO_ROOT", tmp_path)
    _init_git(tmp_path)
    (tmp_path / "image.png").write_bytes(b"PNG" + b"\x00" * 10)
    (tmp_path / "real.py").write_text(f"# Constitutional Hash: {SAMPLE_HASH}\n")
    subprocess.run(["git", "add", "."], cwd=tmp_path, check=True)
    subprocess.run(["git", "commit", "-qm", "init"], cwd=tmp_path, check=True)
    inv = verifier.build_inventory()
    assert "image.png" not in inv
    assert "real.py" in inv


def test_inventory_is_sorted_by_path(tmp_path, monkeypatch):
    monkeypatch.setattr(verifier, "REPO_ROOT", tmp_path)
    _init_git(tmp_path)
    for name in ("z.py", "a.py", "m.py"):
        (tmp_path / name).write_text(f"# Constitutional Hash: {SAMPLE_HASH}\n")
    subprocess.run(["git", "add", "."], cwd=tmp_path, check=True)
    subprocess.run(["git", "commit", "-qm", "init"], cwd=tmp_path, check=True)
    inv = verifier.build_inventory()
    assert list(inv.keys()) == ["a.py", "m.py", "z.py"]


# ---------------------------------------------------------------------------
# Lock file I/O
# ---------------------------------------------------------------------------

def test_write_and_load_lock_round_trip(tmp_path, monkeypatch):
    monkeypatch.setattr(verifier, "LOCK_PATH", tmp_path / "lock.json")
    payload = {"a.py": "abcdef0123456789", "b.py": "1111111111111111"}
    verifier.write_lock(payload)
    assert verifier.load_lock() == payload


def test_load_lock_returns_empty_when_missing(tmp_path, monkeypatch):
    monkeypatch.setattr(verifier, "LOCK_PATH", tmp_path / "absent.json")
    assert verifier.load_lock() == {}


def test_load_lock_rejects_malformed_schema(tmp_path, monkeypatch):
    bad = tmp_path / "bad.json"
    bad.write_text(json.dumps({"wrong_key": {}}))
    monkeypatch.setattr(verifier, "LOCK_PATH", bad)
    with pytest.raises(ValueError, match="missing 'hashes'"):
        verifier.load_lock()


# ---------------------------------------------------------------------------
# diff_inventories
# ---------------------------------------------------------------------------

def test_diff_no_changes():
    assert verifier.diff_inventories({"a": "x"}, {"a": "x"}) == ([], [], [])


def test_diff_detects_added():
    added, removed, changed = verifier.diff_inventories({}, {"a": "x"})
    assert added == ["a"]
    assert removed == [] and changed == []


def test_diff_detects_removed():
    added, removed, changed = verifier.diff_inventories({"a": "x"}, {})
    assert removed == ["a"]
    assert added == [] and changed == []


def test_diff_detects_changed_hash():
    added, removed, changed = verifier.diff_inventories({"a": "old"}, {"a": "new"})
    assert changed == [("a", "old", "new")]
    assert added == [] and removed == []


def test_diff_handles_mixed_delta():
    pinned = {"keep": "k", "drop": "d", "rotate": "r1"}
    actual = {"keep": "k", "add": "a", "rotate": "r2"}
    added, removed, changed = verifier.diff_inventories(pinned, actual)
    assert added == ["add"]
    assert removed == ["drop"]
    assert changed == [("rotate", "r1", "r2")]


def test_filter_ignored_removed_splits_by_prefix():
    enforced, ignored = verifier._filter_ignored_removed(
        ["packages/acgs-lite/a.py", "packages/clinicalguard/b.py"],
        ["packages/clinicalguard"],
    )
    assert enforced == ["packages/acgs-lite/a.py"]
    assert ignored == ["packages/clinicalguard/b.py"]


# ---------------------------------------------------------------------------
# CLI behavior — exit codes + output shape
# ---------------------------------------------------------------------------

def _run_cli(*args, cwd):
    # Invoke the script that lives INSIDE cwd so its __file__-anchored
    # REPO_ROOT resolves to the isolated tree, not the real govern-zone repo.
    script = Path(cwd) / "scripts" / "verify_constitutional_hashes.py"
    return subprocess.run(
        [sys.executable, str(script), *args],
        cwd=str(cwd), capture_output=True, text=True,
    )


def _isolated_tree(tmp_path: Path) -> Path:
    """Set up an isolated repo that mimics the script's layout."""
    repo = tmp_path / "repo"
    (repo / "scripts").mkdir(parents=True)
    (repo / "docs").mkdir()
    # Copy the script in (test exercises it as-installed).
    (repo / "scripts" / "verify_constitutional_hashes.py").write_text(SCRIPT.read_text())
    _init_git(repo)
    subprocess.run(["git", "add", "."], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-qm", "init"], cwd=repo, check=True)
    return repo


def test_cli_print_emits_json(tmp_path):
    repo = _isolated_tree(tmp_path)
    result = _run_cli("--print", cwd=repo)
    assert result.returncode == 0
    parsed = json.loads(result.stdout)
    assert parsed == {"hashes": {}}


def test_cli_update_writes_lock(tmp_path):
    repo = _isolated_tree(tmp_path)
    (repo / "policy.py").write_text(f"# Constitutional Hash: {SAMPLE_HASH}\n")
    subprocess.run(["git", "add", "policy.py"], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-qm", "policy"], cwd=repo, check=True)

    result = _run_cli("--update", cwd=repo)
    assert result.returncode == 0
    lock = json.loads((repo / "docs/constitutional-hashes.lock").read_text())
    assert lock["hashes"] == {"policy.py": SAMPLE_HASH}


def test_cli_clean_verify_exits_zero(tmp_path):
    repo = _isolated_tree(tmp_path)
    _run_cli("--update", cwd=repo)  # establish baseline
    result = _run_cli(cwd=repo)
    assert result.returncode == 0
    assert "verified clean" in result.stdout


def test_cli_drift_exits_one_with_actionable_message(tmp_path):
    repo = _isolated_tree(tmp_path)
    (repo / "policy.py").write_text(f"# Constitutional Hash: {SAMPLE_HASH}\n")
    subprocess.run(["git", "add", "policy.py"], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-qm", "p"], cwd=repo, check=True)
    _run_cli("--update", cwd=repo)

    # Introduce drift: change the declared hash.
    (repo / "policy.py").write_text("# Constitutional Hash: deadbeefcafebabe\n")
    result = _run_cli(cwd=repo)
    assert result.returncode == 1
    assert "FAIL" in result.stdout
    assert "CHANGED" in result.stdout
    assert "--update" in result.stdout  # actionable remediation


def test_cli_detects_removed_marker(tmp_path):
    repo = _isolated_tree(tmp_path)
    (repo / "policy.py").write_text(f"# Constitutional Hash: {SAMPLE_HASH}\n")
    subprocess.run(["git", "add", "policy.py"], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-qm", "p"], cwd=repo, check=True)
    _run_cli("--update", cwd=repo)

    # Strip the marker without re-pinning the lock.
    (repo / "policy.py").write_text("# (marker removed)\n")
    result = _run_cli(cwd=repo)
    assert result.returncode == 1
    assert "REMOVED" in result.stdout


def test_cli_can_explicitly_ignore_removed_prefix(tmp_path):
    repo = _isolated_tree(tmp_path)
    clinical = repo / "packages" / "clinicalguard"
    clinical.mkdir(parents=True)
    policy = clinical / "policy.py"
    policy.write_text(f"# Constitutional Hash: {SAMPLE_HASH}\n")
    subprocess.run(["git", "add", "packages/clinicalguard/policy.py"], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-qm", "clinical"], cwd=repo, check=True)
    _run_cli("--update", cwd=repo)

    subprocess.run(["git", "rm", "-q", "packages/clinicalguard/policy.py"], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-qm", "remove clinical"], cwd=repo, check=True)

    result = _run_cli("--ignore-missing-prefix", "packages/clinicalguard/", cwd=repo)
    assert result.returncode == 0
    assert "WARNING" in result.stdout
    assert "packages/clinicalguard/policy.py" in result.stdout


def test_cli_detects_newly_added_marker(tmp_path):
    repo = _isolated_tree(tmp_path)
    _run_cli("--update", cwd=repo)  # empty baseline

    # Introduce a new sealed file without re-pinning.
    (repo / "new_policy.py").write_text(f"# Constitutional Hash: {SAMPLE_HASH}\n")
    subprocess.run(["git", "add", "new_policy.py"], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-qm", "new"], cwd=repo, check=True)

    result = _run_cli(cwd=repo)
    assert result.returncode == 1
    assert "ADDED" in result.stdout
    assert "new_policy.py" in result.stdout
