"""Round-trip contract: a pack GENERATED by gove-zone must VERIFY offline here.

This is the load-bearing promise of the standalone verifier — an auditor is
handed a proof pack that gove-zone produced and re-checks it on a machine where
gove-zone is not installed. A verifier that only accepts packs it generated
itself proves nothing about shipped evidence.

The pack is produced by a **separate interpreter** (``packages/gove-zone``'s own
virtualenv) driven as a subprocess, so nothing from the ``gove_zone`` namespace
is ever imported into this package's process. The clean-room contract in
``test_cleanroom.py`` (no source module imports ``gove_zone``) is unaffected.

Inputs are gove-zone's committed ``proofpacks/valid-replay`` artifacts and the
generation clock is pinned, matching gove-zone's own byte-reproducible fixture
generator, so the pack under test is exactly what gove-zone ships.

CI note: the gove-zone interpreter (``.venv-gz``) is a local development venv
that is NOT present in a clean ``actions/checkout`` tree. When it is absent,
the round-trip tests SKIP loudly (not silently pass) — a round-trip test that
never runs is exactly the false-green this package exists to prevent.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

from acgs_proofpack_verifier import verify_pack
from acgs_proofpack_verifier.cli import main as cli_main

_TESTS = Path(__file__).parent
_REPO_ROOT = _TESTS.parents[2]
_GOVE_ZONE = _REPO_ROOT / "packages" / "gove-zone"
_GOVE_ZONE_PYTHON = _GOVE_ZONE / ".venv-gz" / "bin" / "python"
_GENERATOR_INPUTS = _GOVE_ZONE / "tests" / "fixtures" / "proofpacks" / "valid-replay"

# Pinned generation clock, identical to gove-zone's golden-fixture generator.
NOW_ISO = "2026-01-01T00:00:00+00:00"

SUMMARY_BINDING_MISMATCH = "SUMMARY_BINDING_MISMATCH"

# Skip the entire module when the gove-zone interpreter is absent (CI).
# A loud skip is correct; a silent pass would be the false-green we prevent.
_HAS_GENERATOR = _GOVE_ZONE_PYTHON.is_file() and _GENERATOR_INPUTS.is_dir()
pytestmark = pytest.mark.skipif(
    not _HAS_GENERATOR,
    reason=f"gove-zone generator interpreter not found at {_GOVE_ZONE_PYTHON} "
    "(local dev venv; absent in CI). Run `uv venv --python 3.11 .venv-gz` in "
    "packages/gove-zone and `uv pip install -e '.[dev,schema,crypto]'` to enable.",
)


@pytest.fixture(scope="module")
def gove_zone_pack(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Generate a real gove-zone proof pack via gove-zone's own interpreter."""
    out = tmp_path_factory.mktemp("gove-zone-pack") / "pack"

    proc = subprocess.run(  # noqa: S603 — fixed argv, no shell, paths are repo-local.
        [
            str(_GOVE_ZONE_PYTHON),
            "-m",
            "gove_zone.proofpack_cli",
            "proofpack",
            "generate",
            "--receipt",
            str(_GENERATOR_INPUTS / "receipts" / "r1.json"),
            "--audit",
            str(_GENERATOR_INPUTS / "audit.jsonl"),
            "--policy-bundle",
            str(_GENERATOR_INPUTS / "policy_bundle.json"),
            "--side-store",
            str(_GENERATOR_INPUTS / "replay_side_store.jsonl"),
            "--out",
            str(out),
            "--now-iso",
            NOW_ISO,
            "--force",
        ],
        cwd=str(_GOVE_ZONE),
        capture_output=True,
        text=True,
        check=False,
    )
    # A generator that did not run is a broken test, never a silent pass.
    assert proc.returncode == 0, (
        f"gove-zone pack generation failed (rc={proc.returncode})\n"
        f"stdout: {proc.stdout}\nstderr: {proc.stderr}"
    )

    summary = out / "verification-summary.md"
    assert summary.is_file(), f"generator produced no verification-summary.md in {out}"
    # Proof that the pack really is gove-zone-generated: its footer carries the
    # gove-zone generator identity, not this package's.
    assert "gove_zone.proofpack" in summary.read_text(encoding="utf-8")
    return out


def test_gove_zone_pack_verifies_programmatically(gove_zone_pack: Path) -> None:
    """The shipped pack must verify — and specifically must not trip the
    summary byte-compare, which re-renders the summary locally."""
    result = verify_pack(gove_zone_pack, now_iso=NOW_ISO)

    assert not any(str(r) == SUMMARY_BINDING_MISMATCH for r in result.reasons), (
        "verifier re-rendered the summary with its own generator identity: "
        f"{[str(r) for r in result.reasons]}"
    )
    assert result.valid, [str(r) for r in result.reasons]
    assert result.reasons == []


def test_cli_verifies_gove_zone_pack_exit_zero(gove_zone_pack: Path, capsys) -> None:
    rc = cli_main(["proofpack", "verify", str(gove_zone_pack), "--now-iso", NOW_ISO])
    out = json.loads(capsys.readouterr().out)

    assert SUMMARY_BINDING_MISMATCH not in [str(r) for r in out["reasons"]], out["reasons"]
    assert rc == 0, out
    assert out["valid"] is True, out


def test_forged_summary_body_is_rejected(gove_zone_pack: Path) -> None:
    """Adversarial: the footer-excision must NOT weaken substantive tamper
    detection. Editing the summary BODY (above the ``---`` footer separator)
    must still trip SUMMARY_BINDING_MISMATCH."""
    import shutil

    forged = gove_zone_pack.parent / "forged-pack"
    shutil.copytree(gove_zone_pack, forged)
    summary = forged / "verification-summary.md"
    text = summary.read_text(encoding="utf-8")
    # Tamper with the substantive body, not the footer.
    body, sep, footer = text.rpartition("\n---\n")
    assert sep, "summary has no --- footer separator"
    tampered_body = body.replace("PASS", "FAIL", 1)
    if tampered_body == body:
        tampered_body = body + "\n<!-- injected -->"
    summary.write_text(tampered_body + sep + footer, encoding="utf-8")

    result = verify_pack(forged, now_iso=NOW_ISO)
    assert not result.valid, "forged summary body was accepted"
    assert any(str(r) == SUMMARY_BINDING_MISMATCH for r in result.reasons), (
        "expected SUMMARY_BINDING_MISMATCH for a tampered body, got "
        f"{[str(r) for r in result.reasons]}"
    )
