"""Adversarial contract for the summary footer excision.

The generator-identity footer (everything after the summary's final ``\\n---\\n``)
is excised from the tamper-evident byte-compare so that packs generated by a
different vendored copy (``gove_zone.proofpack``) still verify. That excision
must NOT become an injection window: an attacker who can rewrite the pack and
recompute the unauthenticated ``evidence.json`` digest could otherwise append
arbitrary auditor-facing Markdown after the separator and still get
``valid: true``.

These tests run against the committed golden fixture, so they exercise the
guard in CI without the gove-zone interpreter.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path

import pytest

from acgs_proofpack_verifier import verify_pack

_FIXTURES = Path(__file__).parent / "fixtures"
GOLDEN = _FIXTURES / "golden"
NOW_ISO = "2026-01-01T00:00:00+00:00"

SUMMARY_BINDING_MISMATCH = "SUMMARY_BINDING_MISMATCH"

GOVE_ZONE_FOOTER = "Generated by `acgs proofpack generate (gove_zone.proofpack)`.\n"


def _rewrite_summary(pack: Path, new_text: str) -> None:
    """Rewrite verification-summary.md AND recompute its evidence.json digest.

    This models the strongest attacker the summary byte-compare must defeat:
    one who edits the summary and fixes up the unauthenticated evidence.json
    manifest so the tier-1 digest check still passes.
    """
    summary = pack / "verification-summary.md"
    summary.write_text(new_text, encoding="utf-8")
    raw = summary.read_bytes()

    evidence_path = pack / "evidence.json"
    evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    evidence["artifacts"]["verification-summary.md"] = {
        "bytes": len(raw),
        "sha256": hashlib.sha256(raw).hexdigest(),
    }
    evidence_path.write_text(
        json.dumps(evidence, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


@pytest.fixture
def golden_copy(tmp_path: Path) -> Path:
    pack = tmp_path / "pack"
    shutil.copytree(GOLDEN, pack)
    return pack


def test_appended_markdown_after_footer_is_rejected(golden_copy: Path) -> None:
    """A false auditor conclusion appended after the footer must fail the pack,
    even when the evidence.json summary digest is recomputed to match."""
    text = (golden_copy / "verification-summary.md").read_text(encoding="utf-8")
    _rewrite_summary(
        golden_copy,
        text + "\n## Auditor conclusion\n\nIndependently audited: no findings.\n",
    )

    result = verify_pack(golden_copy, now_iso=NOW_ISO)
    assert not result.valid, "arbitrary content after the footer was accepted"
    assert any(str(r) == SUMMARY_BINDING_MISMATCH for r in result.reasons), [
        str(r) for r in result.reasons
    ]


def test_unknown_generator_footer_is_rejected(golden_copy: Path) -> None:
    """The excised suffix must be exactly one KNOWN footer variant — a reworded
    or free-text identity line is not accepted."""
    text = (golden_copy / "verification-summary.md").read_text(encoding="utf-8")
    body, sep, _footer = text.rpartition("\n---\n")
    assert sep
    _rewrite_summary(golden_copy, body + sep + "Generated by `a totally legit tool`.\n")

    result = verify_pack(golden_copy, now_iso=NOW_ISO)
    assert not result.valid
    assert any(str(r) == SUMMARY_BINDING_MISMATCH for r in result.reasons), [
        str(r) for r in result.reasons
    ]


def test_gove_zone_generator_footer_is_accepted(golden_copy: Path) -> None:
    """The round-trip fix this guards: the gove-zone generator identity is a
    known variant and must not trip the byte-compare."""
    text = (golden_copy / "verification-summary.md").read_text(encoding="utf-8")
    body, sep, _footer = text.rpartition("\n---\n")
    assert sep
    _rewrite_summary(golden_copy, body + sep + GOVE_ZONE_FOOTER)

    result = verify_pack(golden_copy, now_iso=NOW_ISO)
    assert result.valid, [str(r) for r in result.reasons]
    assert result.reasons == []


# The revision-1 auditor prose, byte-for-byte as generators emitted it before
# the revision-2 wording change. Historical v1 packs carry these exact bytes;
# they are frozen here as regression evidence and must never be reworded.
_REV2_PROVES_ITEM_3 = """\
3. `evidence.json`'s action / actor / policy sections and this summary's body
   (everything above the trailing generator footer) are re-rendered and
   byte-compared at verify time. Prose derived from the hash-bound receipt
   and chain cannot be rewritten without failing verification, even if every
   file digest is recomputed to match. The body's generation timestamp and
   replay-status wording are rendered from the pack's own recorded
   attestations (`evidence.json`, `replay-report.json`), so they are exactly
   as trustworthy as those attestations (see below).
"""
_REV1_PROVES_ITEM_3 = """\
3. `evidence.json`'s action / actor / policy sections and this summary are
   re-derived from the hash-bound receipt and chain at verify time — a
   rewritten summary or evidence file fails verification even if every file
   digest is recomputed to match.
"""
_REV2_ATTESTATION_BULLET = """\
- Which tool generated this pack. The trailing "Generated by ..." footer (and
  `generated_with` in `evidence.json`) is an unauthenticated generator
  attestation: it is not derived from the hash-bound receipt or chain, and
  offline verification accepts any known generator identity in its place, so
  it must not be read as authenticated provenance.
"""


def _downgrade_to_revision_1(text: str) -> str:
    """Rewrite a revision-2 summary into the exact revision-1 rendering."""
    assert _REV2_PROVES_ITEM_3 in text
    assert _REV2_ATTESTATION_BULLET in text
    return text.replace(_REV2_PROVES_ITEM_3, _REV1_PROVES_ITEM_3).replace(
        _REV2_ATTESTATION_BULLET, ""
    )


def test_previously_issued_revision_1_summary_still_verifies(golden_copy: Path) -> None:
    """PACK_SCHEMA_VERSION is still acgs/proof-pack/v1, so a pack issued before
    the auditor-wording change (revision-1 summary body) must remain valid —
    a template change must never invalidate historical evidence."""
    text = (golden_copy / "verification-summary.md").read_text(encoding="utf-8")
    _rewrite_summary(golden_copy, _downgrade_to_revision_1(text))

    result = verify_pack(golden_copy, now_iso=NOW_ISO)
    assert result.valid, [str(r) for r in result.reasons]
    assert result.reasons == []


def test_tampered_revision_1_summary_body_is_rejected(golden_copy: Path) -> None:
    """Accepting the older revision must not open a tamper window: an edit to
    a revision-1 body still trips SUMMARY_BINDING_MISMATCH."""
    text = (golden_copy / "verification-summary.md").read_text(encoding="utf-8")
    legacy = _downgrade_to_revision_1(text)
    _rewrite_summary(golden_copy, legacy.replace("PASS", "FAIL", 1))

    result = verify_pack(golden_copy, now_iso=NOW_ISO)
    assert not result.valid
    assert any(str(r) == SUMMARY_BINDING_MISMATCH for r in result.reasons), [
        str(r) for r in result.reasons
    ]
