/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/bus/healthz': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Healthz */
    get: operations['healthz_api_bus_healthz_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/bus/receipts/{receipt_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Receipt Proof */
    get: operations['get_receipt_proof_api_bus_receipts__receipt_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/bus/traces': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Traces */
    get: operations['list_traces_api_bus_traces_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/bus/traces/{correlation_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Trace */
    get: operations['get_trace_api_bus_traces__correlation_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * Event
     * @description One captured event. data-model.md §Event.
     */
    Event: {
      /** Audit Receipt Hash */
      audit_receipt_hash?: string | null
      /** Causal Index */
      causal_index: number
      /**
       * Constitutional Hash
       * @description 16-char hex form
       */
      constitutional_hash: string
      /** Correlation Id */
      correlation_id: string
      /** Decision */
      decision?: ('allow' | 'deny' | 'transform' | 'escalate') | null
      /**
       * Event Hash
       * @description SHA-256 hex digest
       */
      event_hash: string
      /** Event Id */
      event_id: string
      /** Flagged Rule */
      flagged_rule?: string | null
      /** Gap Ended At */
      gap_ended_at?: string | null
      /** Gap Started At */
      gap_started_at?: string | null
      /**
       * Kind
       * @enum {string}
       */
      kind: 'dispatch' | 'response' | 'decision'
      /** Payload Ref */
      payload_ref: string
      /** Phoenix Parent Span Id */
      phoenix_parent_span_id?: string | null
      /** Phoenix Span Id */
      phoenix_span_id?: string | null
      /** Phoenix Trace Id */
      phoenix_trace_id?: string | null
      /** Prev Hash */
      prev_hash?: string | null
      /**
       * Recorded At
       * Format: date-time
       */
      recorded_at: string
      /** Source Agent */
      source_agent: string
      /**
       * Status
       * @enum {string}
       */
      status:
        | 'completed'
        | 'policy-violation'
        | 'dispatch-failure'
        | 'unwired-handler'
        | 'orphan-response'
        | 'incomplete-pair'
        | 'ingest-gap'
      /** Target Handler Declared */
      target_handler_declared?: string | null
      /** Target Handler Resolved */
      target_handler_resolved?: string | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * ReceiptProof
     * @description Console-ready proof packet for one receipt or receipt hash.
     */
    ReceiptProof: {
      /** Correlation Id */
      correlation_id: string
      /** Decision */
      decision?: ('allow' | 'deny' | 'transform' | 'escalate') | null
      /** Events */
      events: components['schemas']['Event'][]
      /** Flagged Rules */
      flagged_rules: string[]
      /** Hash Chain Verified */
      hash_chain_verified: boolean
      /**
       * Integrity Status
       * @enum {string}
       */
      integrity_status: 'intact' | 'tampered' | 'unknown'
      /**
       * Kind
       * @default receipt-proof
       * @constant
       */
      kind: 'receipt-proof'
      /** Phoenix Parent Span Id */
      phoenix_parent_span_id?: string | null
      /** Phoenix Span Id */
      phoenix_span_id?: string | null
      /** Phoenix Trace Id */
      phoenix_trace_id?: string | null
      /** Policy Path */
      policy_path: string[]
      /** Receipt Hash */
      receipt_hash: string
      /** Receipt Id */
      receipt_id: string
      /** Signed Evidence Packet */
      signed_evidence_packet: string
      trace: components['schemas']['TraceListItem']
    }
    /** SingleTrace */
    SingleTrace: {
      /** Events */
      events?: components['schemas']['Event'][]
      /**
       * Integrity Status
       * @enum {string}
       */
      integrity_status: 'intact' | 'tampered' | 'unknown'
      /**
       * Kind
       * @default single-trace
       * @constant
       */
      kind: 'single-trace'
      /** Rotation At Index */
      rotation_at_index?: number | null
      trace: components['schemas']['TraceListItem']
    }
    /** TraceList */
    TraceList: {
      /** Items */
      items?: components['schemas']['TraceListItem'][]
      /**
       * Kind
       * @default trace-list
       * @constant
       */
      kind: 'trace-list'
      /** Next Cursor */
      next_cursor?: string | null
    }
    /** TraceListItem */
    TraceListItem: {
      /** Completed At */
      completed_at?: string | null
      /**
       * Constitutional Hash
       * @description 16-char hex form
       */
      constitutional_hash: string
      /** Correlation Id */
      correlation_id: string
      /** Event Count */
      event_count: number
      /**
       * Integrity Status
       * @enum {string}
       */
      integrity_status: 'intact' | 'tampered' | 'unknown'
      /** Phoenix Parent Span Id */
      phoenix_parent_span_id?: string | null
      /** Phoenix Span Id */
      phoenix_span_id?: string | null
      /** Phoenix Trace Id */
      phoenix_trace_id?: string | null
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      /**
       * Worst Event Status
       * @enum {string}
       */
      worst_event_status:
        | 'completed'
        | 'policy-violation'
        | 'dispatch-failure'
        | 'unwired-handler'
        | 'orphan-response'
        | 'incomplete-pair'
        | 'ingest-gap'
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  healthz_api_bus_healthz_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
  get_receipt_proof_api_bus_receipts__receipt_id__get: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path: {
        receipt_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReceiptProof']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_traces_api_bus_traces_get: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TraceList']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_trace_api_bus_traces__correlation_id__get: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path: {
        correlation_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SingleTrace']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
