"""Smoke gate for the compliance mapping engine artifacts.

Keeps ``compliance/control-mapping.json`` and the generated readiness report
from rotting: the mapping must validate under the engine's own schema, every
requirement must carry the four contract fields with an allowed status, and
the report must exist, carry the honesty disclaimer, and stay regenerable.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "compliance"))

import engine  # noqa: E402


def test_mapping_validates_under_engine_schema() -> None:
    mapping = engine.load_mapping()
    assert engine.validate_schema(mapping) == []


def test_every_requirement_carries_the_contract_fields() -> None:
    mapping = engine.load_mapping()
    for fw in mapping["frameworks"].values():
        for entry in fw["requirements"]:
            for field in ("requirement", "evidence_source", "verification_method", "status"):
                assert entry[field], f"{entry['id']}: empty {field}"
            assert entry["status"] in engine.ALLOWED_STATUSES


def test_all_four_target_frameworks_are_mapped() -> None:
    mapping = engine.load_mapping()
    assert set(mapping["frameworks"]) == {"eu_ai_act", "nist_ai_rmf", "iso_42001", "soc2"}
    for fw in mapping["frameworks"].values():
        assert fw["requirements"], f"{fw['name']}: no requirements mapped"


def test_report_exists_and_carries_the_honesty_disclaimer() -> None:
    report = (ROOT / "compliance" / "COMPLIANCE_READINESS_REPORT.md").read_text(encoding="utf-8")
    assert "Not compliance-certified" in report
    assert "Generated by `compliance/engine.py`" in report


def test_report_generation_is_deterministic_apart_from_header() -> None:
    """generate_report must run cleanly and cover every mapped requirement."""
    mapping = engine.load_mapping()
    missing = engine.check_evidence_paths(mapping)
    text = engine.generate_report(mapping, missing, verifications=None)
    for fw in mapping["frameworks"].values():
        for entry in fw["requirements"]:
            assert entry["id"] in text
